In [ ]:
import requests
import json
import pandas as pd
import base64

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/peopleRelationships?limit=100&offset=0"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
with open(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\people_relationships.json', 'w') as file:
    json.dump(data, file, indent=4)
    
total = data['_metadata']['total']
list_of_offsets = list(range(0, round(total, -1) + 1, 100))

df_list = []

from pymongo import MongoClient
client = MongoClient()
db = client.Christina
collection = db.followupboss_people_relationships

def insert_one_document(data):
    collection.insert_one(data)
    
def insert_one_document(data):
    collection.insert_one(data)
    
for i in list_of_offsets:
    url = f"https://api.followupboss.com/v1/peopleRelationships?limit=100&offset={i}"

    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['peoplerelationships']:
        if isinstance(x, dict):
            insert_one_document(x)

In [3]:
from pymongo import MongoClient
client = MongoClient()
db = client.Christina
collection = db.followupboss_people_relationships

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

delete_all()

Deleted 458 documents from followupboss_people_relationships

In [4]:
from datetime import datetime as dt
import requests
import json
import pandas as pd
import base64

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
total = data["_metadata"]["total"]
    
from pymongo import MongoClient
client = MongoClient()
db = client.Christina
collection = db.followupboss_people

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_collections():
    print(f"There are {collection.count_documents({})} documents now in {collection.name}")
    
delete_all()

list_of_offsets = list(range(0, round(total, -2) + 1, 100))
date_now = dt.today().strftime('%m/%d/%Y')

for i in list_of_offsets:
    url = f'https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset={i}&includeTrash=false&includeUnclaimed=false'
    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['people']:
        if isinstance(x, dict):
            insert_one_document(x)
            
count_of_all_collections()

Deleted 0 documents from followupboss_people

InvalidSchema: No connection adapters were found for '"https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"'

In [5]:
url

'"https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"'

In [7]:
from pymongo import MongoClient
from bson.objectid import ObjectId  # Import ObjectId

# Assuming you've already connected to MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['Christina']
collection = db['followupboss_people_relationships']

def view_document_by_id(object_id_str):
    try:
        object_id = ObjectId(object_id_str)  # Convert the string to ObjectId
        document = collection.find_one({"_id": object_id})  # Find the document
        if document:
            print(document)
        else:
            print(f"No document found with ObjectId: {object_id_str}")
    except Exception as e:
        print(f"Error: {e}")

# Example usage
view_document_by_id("671109bb72daf9da3b33c261")

{'_id': ObjectId('671109bb72daf9da3b33c261'), 'id': 718, 'created': '2024-08-28T18:49:45Z', 'updated': '2024-08-28T18:49:45Z', 'createdById': 1, 'updatedById': 1, 'personId': 13197, 'name': 'Carole Projahn', 'firstName': 'Carole', 'lastName': 'Projahn', 'type': 'Wife', 'isPriority': True, 'emails': [{'value': 'cprojahn@icloud.com', 'type': 'home', 'status': 'Valid', 'isPrimary': 1}], 'phones': [], 'addresses': [], 'picture': None, 'socialData': []}

In [12]:
from pymongo import MongoClient
from bson.objectid import ObjectId  # Import ObjectId

# Assuming you've already connected to MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['Christina']
collection = db['followupboss_people']

def view_document_by_id(value):
    try:
        document = collection.find_one({"id": value})  # Find the document
        if document:
            print(document)
        else:
            print(f"No document found with ObjectId: {value}")
    except Exception as e:
        print(f"Error: {e}")

# Example usage
view_document_by_id(13197)

{'_id': ObjectId('67110c03ae5f22d55bf8e80e'), 'id': 13197, 'created': '2024-08-24T16:27:46Z', 'updated': '2024-09-24T15:32:11Z', 'createdVia': 'API', 'lastActivity': '2024-10-08T17:45:24Z', 'name': 'Scott Projahn', 'firstName': 'Scott', 'lastName': 'Projahn', 'stage': 'C - Cold 6-12 Months', 'stageId': 50, 'source': '<unspecified>', 'sourceId': 1, 'sourceUrl': '', 'leadFlowId': 20, 'delayed': False, 'contacted': 1, 'price': None, 'assignedLenderId': None, 'assignedLenderName': None, 'assignedUserId': 1, 'assignedPondId': None, 'assignedTo': 'Christina James', 'tags': ['Google Meet', 'mls search'], 'emails': [{'value': 'scottprojahn@gmail.com', 'type': 'home', 'status': 'Valid', 'isPrimary': 1}, {'value': 'cprojahn@icloud.com', 'type': 'home', 'status': 'Valid', 'isPrimary': 1}], 'phones': [{'value': '4076205108', 'type': 'mobile', 'status': 'Valid', 'isPrimary': 1, 'normalized': '4076205108', 'isLandline': False, 'isOnboardingNumber': False}], 'addresses': [], 'picture': None, 'socialData': [], 'websiteVisits': 0, 'timeframeId': None, 'timeframeUpdated': None, 'timeframeStatus': None, 'claimed': True, 'dealStatus': None, 'dealStage': None, 'dealName': None, 'dealCloseDate': None, 'dealPrice': None, 'firstToClaimOffer': False, 'collaborators': [{'id': 1, 'name': 'Christina James', 'assigned': True, 'role': 'Broker'}, {'id': 7, 'name': 'Jaki Ahlemeyer', 'assigned': False, 'role': 'Agent'}], 'teamLeaders': [], 'pondMembers': []}

In [60]:
from pymongo import MongoClient
import pandas as pd

# Connect to MongoDB (adjust the connection string as needed)
client = MongoClient('mongodb://localhost:27017/')
db = client['Christina']
collection = db['followupboss_people_relationships']

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

# Example usage
df = get_all_data_as_dataframe()

from pymongoarrow.api import find_pandas_all
from pymongo import MongoClient
import pandas as pd

# Connect to MongoDB
client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_relationships']

# Define the fields you want to extract
projection = {
    'id': 1,
    'firstName': 1,
    'lastName': 1,
    'type': 1,
    'phones.value': 1,
    'phones.type': 1,
    'emails.value': 1,
    'emails.type': 1,
    'addresses.street': 1,
    'addresses.city': 1,
    'addresses.state': 1,
    'addresses.code': 1,
    'addresses.country': 1,
    'addresses.type': 1
}

# Use find_pandas_all to query MongoDB and get a DataFrame
df = find_pandas_all(collection, {}, projection=projection)

# Limit the number of phones to 6
df['phones'] = df['phones'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['emails'] = df['emails'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['addresses'] = df['addresses'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])


# Create separate columns for the first 6 phones
for i in range(6):
    df[f'phone_{i+1}'] = df['phones'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'phone_type_{i+1}'] = df['phones'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'email_{i+1}'] = df['emails'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'email_type_{i+1}'] = df['emails'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'address_street_{i+1}'] = df['addresses'].apply(lambda x: x[i]['street'] if len(x) > i else None)
    df[f'address_city_{i+1}'] = df['addresses'].apply(lambda x: x[i]['city'] if len(x) > i else None)
    df[f'address_state_{i+1}'] = df['addresses'].apply(lambda x: x[i]['state'] if len(x) > i else None)
    df[f'address_code_{i+1}'] = df['addresses'].apply(lambda x: x[i]['code'] if len(x) > i else None)
    df[f'address_country_{i+1}'] = df['addresses'].apply(lambda x: x[i]['country'] if len(x) > i else None)
    df[f'address_type_{i+1}'] = df['addresses'].apply(lambda x: x[i]['type'] if len(x) > i else None)

# Drop the original 'phones' column if not needed
df.drop(columns=['phones'], inplace=True)
df.drop(columns=['emails'], inplace=True)
df.drop(columns=['addresses'], inplace=True)

# Display the DataFrame
df['Update Source'] = "Followup boss"
df.columns = [
    "Mongodb ID",
"People ID From FB",
"Relationship First Name",
"Relationship Last Name",
"Relationship Type",
"Relationship Phone 1",
"Relationship Phone 1 - Type",
"Relationship Phone 2",
"Relationship Phone 2 - Type",
"Relationship Phone 3",
"Relationship Phone 3 - Type",
"Relationship Phone 4",
"Relationship Phone 4 - Type",
"Relationship Phone 5",
"Relationship Phone 5 - Type",
"Relationship Phone 6",
"Relationship Phone 6 - Type",
"Relationship Email 1",
"Relationship Email 1 - Type",
"Relationship Email 2",
"Relationship Email 2 - Type",
"Relationship Email 3",
"Relationship Email 3 - Type",
"Relationship Email 4",
"Relationship Email 4 - Type",
"Relationship Email 5",
"Relationship Email 5 - Type",
"Relationship Email 6",
"Relationship Email 6 - Type",
"Relationship Address 1 - Street",
"Relationship Address 1 - City",
"Relationship Address 1 - State",
"Relationship Address 1 - Zip",
"Relationship Address 1 - Country",
"Relationship Address 1 - Type",
"Relationship Address 2 - Street",
"Relationship Address 2 - City",
"Relationship Address 2 - State",
"Relationship Address 2 - Zip",
"Relationship Address 2 - Country",
"Relationship Address 2 - Type",
"Relationship Address 3 - Street",
"Relationship Address 3 - City",
"Relationship Address 3 - State",
"Relationship Address 3 - Zip",
"Relationship Address 3 - Country",
"Relationship Address 3 - Type",
"Relationship Address 4 - Street",
"Relationship Address 4 - City",
"Relationship Address 4 - State",
"Relationship Address 4 - Zip",
"Relationship Address 4 - Country",
"Relationship Address 4 - Type",
"Relationship Address 5 - Street",
"Relationship Address 5 - City",
"Relationship Address 5 - State",
"Relationship Address 5 - Zip",
"Relationship Address 5 - Country",
"Relationship Address 5 - Type",
"Relationship Address 6 - Street",
"Relationship Address 6 - City",
"Relationship Address 6 - State",
"Relationship Address 6 - Zip",
"Relationship Address 6 - Country",
"Relationship Address 6 - Type",
"Update Source"
]
df

,Mongodb ID,People ID From FB,Relationship First Name,Relationship Last Name,Relationship Type,Relationship Phone 1,Relationship Phone 1 - Type,Relationship Phone 2,Relationship Phone 2 - Type,Relationship Phone 3,...,Relationship Address 5 - Zip,Relationship Address 5 - Country,Relationship Address 5 - Type,Relationship Address 6 - Street,Relationship Address 6 - City,Relationship Address 6 - State,Relationship Address 6 - Zip,Relationship Address 6 - Country,Relationship Address 6 - Type,Update Source
0,6713727cfc08cff3d068d4d4,732,David,Hooker,,None,None,hkr_dv@yahoo.com,home,None,...,None,None,None,None,None,None,None,None,None,Followup boss
1,6713727cfc08cff3d068d4d5,731,Todd,Seay,,205640-6100,mobile,TSeay@metrobankpc.com,home,None,...,None,None,None,None,None,None,None,None,None,Followup boss
2,6713727cfc08cff3d068d4d6,730,Vicki Smith,,,205-283-4366,mobile,None,None,None,...,None,None,None,None,None,None,None,None,None,Followup boss
3,6713727cfc08cff3d068d4d7,729,Thomas,Webb,Co-op,2057908496,mobile,None,None,None,...,None,None,None,None,None,None,None,None,None,Followup boss
4,6713727cfc08cff3d068d4d8,728,Richard,Hicks,Spouse,2052599959,mobile,None,None,None,...,None,None,None,None,None,None,None,None,None,Followup boss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,67137280fc08cff3d068d69b,37,Claudia,,,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Followup boss
456,67137280fc08cff3d068d69c,36,Blake,,,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,Followup boss
457,67137280fc08cff3d068d69d,28,Kenny,,,2054419395,mobile,kennyjames169@yahoo.com,home,None,...,None,None,None,None,None,None,None,None,None,Followup boss
458,67137280fc08cff3d068d69e,2,Support,,,(855) 622-5311,work,support@followupboss.com,work,None,...,None,None,None,None,None,None,None,None,None,Followup boss
459,67137280fc08cff3d068d69f,1,Sales,,,(855) 888-9769,work,hi@followupboss.com,work,None,...,None,None,None,None,None,None,None,None,None,Followup boss

In [52]:
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
import numpy as np
import uuid

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")

# Get all data in the sheet
data = sheet.get_all_values()

# Convert the data into a pandas DataFrame
df_1 = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_1[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['People ID From FB'] = df['People ID From FB'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people relationships from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='People ID From FB', right_on='ID')
print(f'length of rows of people relationships from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new = df_new[[
    "Lead ID",
    "Relationship First Name",
    "Relationship Last Name",
    "Relationship Type",
    "Relationship Phone 1",
    "Relationship Phone 1 - Type",
    "Relationship Phone 2",
    "Relationship Phone 2 - Type",
    "Relationship Phone 3",
    "Relationship Phone 3 - Type",
    "Relationship Phone 4",
    "Relationship Phone 4 - Type",
    "Relationship Phone 5",
    "Relationship Phone 5 - Type",
    "Relationship Phone 6",
    "Relationship Phone 6 - Type",
    "Relationship Email 1",
    "Relationship Email 1 - Type",
    "Relationship Email 2",
    "Relationship Email 2 - Type",
    "Relationship Email 3",
    "Relationship Email 3 - Type",
    "Relationship Email 4",
    "Relationship Email 4 - Type",
    "Relationship Email 5",
    "Relationship Email 5 - Type",
    "Relationship Email 6",
    "Relationship Email 6 - Type",
    "Relationship Address 1 - Street",
    "Relationship Address 1 - City",
    "Relationship Address 1 - State",
    "Relationship Address 1 - Zip",
    "Relationship Address 1 - Country",
    "Relationship Address 1 - Type",
    "Relationship Address 2 - Street",
    "Relationship Address 2 - City",
    "Relationship Address 2 - State",
    "Relationship Address 2 - Zip",
    "Relationship Address 2 - Country",
    "Relationship Address 2 - Type",
    "Relationship Address 3 - Street",
    "Relationship Address 3 - City",
    "Relationship Address 3 - State",
    "Relationship Address 3 - Zip",
    "Relationship Address 3 - Country",
    "Relationship Address 3 - Type",
    "Relationship Address 4 - Street",
    "Relationship Address 4 - City",
    "Relationship Address 4 - State",
    "Relationship Address 4 - Zip",
    "Relationship Address 4 - Country",
    "Relationship Address 4 - Type",
    "Relationship Address 5 - Street",
    "Relationship Address 5 - City",
    "Relationship Address 5 - State",
    "Relationship Address 5 - Zip",
    "Relationship Address 5 - Country",
    "Relationship Address 5 - Type",
    "Relationship Address 6 - Street",
    "Relationship Address 6 - City",
    "Relationship Address 6 - State",
    "Relationship Address 6 - Zip",
    "Relationship Address 6 - Country",
    "Relationship Address 6 - Type",
    "People ID From FB",
    "Update Source"
]]
df_new

length of rows of people relationships from followup boss before merge: 460
length of rows of people relationships from followup boss after merge: 460

C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_12560\3112362924.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_12560\3112362924.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_12560\3112362924.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id.dropna(subset=['ID'], inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_12560\3112362924.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'] = unique_people_id['ID'].astype(int)

,Lead ID,Relationship First Name,Relationship Last Name,Relationship Type,Relationship Phone 1,Relationship Phone 1 - Type,Relationship Phone 2,Relationship Phone 2 - Type,Relationship Phone 3,Relationship Phone 3 - Type,...,Relationship Address 5 - Country,Relationship Address 5 - Type,Relationship Address 6 - Street,Relationship Address 6 - City,Relationship Address 6 - State,Relationship Address 6 - Zip,Relationship Address 6 - Country,Relationship Address 6 - Type,People ID From FB,Update Source
0,f51rh33n,David,Hooker,,None,None,hkr_dv@yahoo.com,home,None,None,...,None,None,None,None,None,None,None,None,732,Followup boss
1,l75me99v,Todd,Seay,,205640-6100,mobile,TSeay@metrobankpc.com,home,None,None,...,None,None,None,None,None,None,None,None,731,Followup boss
2,z84mh14p,Vicki Smith,,,205-283-4366,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,730,Followup boss
3,a33vb62h,Thomas,Webb,Co-op,2057908496,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,729,Followup boss
4,x32ht82q,Richard,Hicks,Spouse,2052599959,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,728,Followup boss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,eb49e9a4,Claudia,,,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,37,Followup boss
456,l31qu45x,Blake,,,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,36,Followup boss
457,i74uu60v,Kenny,,,2054419395,mobile,kennyjames169@yahoo.com,home,None,None,...,None,None,None,None,None,None,None,None,28,Followup boss
458,e23la84w,Support,,,(855) 622-5311,work,support@followupboss.com,work,None,None,...,None,None,None,None,None,None,None,None,2,Followup boss
459,e16569e7,Sales,,,(855) 888-9769,work,hi@followupboss.com,work,None,None,...,None,None,None,None,None,None,None,None,1,Followup boss

In [54]:
df_old = r"C:\Users\ENDUSER\Downloads\Realtor Tracker Inventory - Leads (1).csv"
df_old = pd.read_csv(df_old)
df_old

df_new_2 = pd.concat([df_new, df_old], ignore_index=True)
df_new_2

,Lead ID,Relationship First Name,Relationship Last Name,Relationship Type,Relationship Phone 1,Relationship Phone 1 - Type,Relationship Phone 2,Relationship Phone 2 - Type,Relationship Phone 3,Relationship Phone 3 - Type,...,Relationship Address 5 - Country,Relationship Address 5 - Type,Relationship Address 6 - Street,Relationship Address 6 - City,Relationship Address 6 - State,Relationship Address 6 - Zip,Relationship Address 6 - Country,Relationship Address 6 - Type,People ID From FB,Update Source
0,f51rh33n,David,Hooker,,None,None,hkr_dv@yahoo.com,home,None,None,...,None,None,None,None,None,None,None,None,732.0,Followup boss
1,l75me99v,Todd,Seay,,205640-6100,mobile,TSeay@metrobankpc.com,home,None,None,...,None,None,None,None,None,None,None,None,731.0,Followup boss
2,z84mh14p,Vicki Smith,,,205-283-4366,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,730.0,Followup boss
3,a33vb62h,Thomas,Webb,Co-op,2057908496,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,729.0,Followup boss
4,x32ht82q,Richard,Hicks,Spouse,2052599959,mobile,None,None,None,None,...,None,None,None,None,None,None,None,None,728.0,Followup boss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,i74uu60v,Kenny,,,2054419395,mobile,kennyjames169@yahoo.com,home,None,None,...,None,None,None,None,None,None,None,None,28.0,Followup boss
458,e23la84w,Support,,,(855) 622-5311,work,support@followupboss.com,work,None,None,...,None,None,None,None,None,None,None,None,2.0,Followup boss
459,e16569e7,Sales,,,(855) 888-9769,work,hi@followupboss.com,work,None,None,...,None,None,None,None,None,None,None,None,1.0,Followup boss
460,cb7f094b,Cindy L. Wilkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,App
461,r55ri47n,Cindy L. Wilkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,App

In [58]:
import pandas as pd

# Step 1: Group by 'Lead ID' and create a row number within each group
df_new_2['Row Number'] = df_new_2.groupby('Lead ID').cumcount() + 1

# Step 2: Concatenate 'Lead ID' with the row number to create 'Relationship ID'
df_new_2['Relationship ID'] = df_new_2['Lead ID'] + '-' + df_new_2['Row Number'].astype(str)
df_new_2.replace([np.inf, -np.inf, np.nan], '', inplace=True)

# Resulting DataFrame
df_people_relationships = df_new_2[[
    "Lead ID",
    "Relationship ID",
    "Relationship First Name",
    "Relationship Last Name",
    "Relationship Type",
    "Relationship Phone 1",
    "Relationship Phone 1 - Type",
    "Relationship Phone 2",
    "Relationship Phone 2 - Type",
    "Relationship Phone 3",
    "Relationship Phone 3 - Type",
    "Relationship Phone 4",
    "Relationship Phone 4 - Type",
    "Relationship Phone 5",
    "Relationship Phone 5 - Type",
    "Relationship Phone 6",
    "Relationship Phone 6 - Type",
    "Relationship Email 1",
    "Relationship Email 1 - Type",
    "Relationship Email 2",
    "Relationship Email 2 - Type",
    "Relationship Email 3",
    "Relationship Email 3 - Type",
    "Relationship Email 4",
    "Relationship Email 4 - Type",
    "Relationship Email 5",
    "Relationship Email 5 - Type",
    "Relationship Email 6",
    "Relationship Email 6 - Type",
    "Relationship Address 1 - Street",
    "Relationship Address 1 - City",
    "Relationship Address 1 - State",
    "Relationship Address 1 - Zip",
    "Relationship Address 1 - Country",
    "Relationship Address 1 - Type",
    "Relationship Address 2 - Street",
    "Relationship Address 2 - City",
    "Relationship Address 2 - State",
    "Relationship Address 2 - Zip",
    "Relationship Address 2 - Country",
    "Relationship Address 2 - Type",
    "Relationship Address 3 - Street",
    "Relationship Address 3 - City",
    "Relationship Address 3 - State",
    "Relationship Address 3 - Zip",
    "Relationship Address 3 - Country",
    "Relationship Address 3 - Type",
    "Relationship Address 4 - Street",
    "Relationship Address 4 - City",
    "Relationship Address 4 - State",
    "Relationship Address 4 - Zip",
    "Relationship Address 4 - Country",
    "Relationship Address 4 - Type",
    "Relationship Address 5 - Street",
    "Relationship Address 5 - City",
    "Relationship Address 5 - State",
    "Relationship Address 5 - Zip",
    "Relationship Address 5 - Country",
    "Relationship Address 5 - Type",
    "Relationship Address 6 - Street",
    "Relationship Address 6 - City",
    "Relationship Address 6 - State",
    "Relationship Address 6 - Zip",
    "Relationship Address 6 - Country",
    "Relationship Address 6 - Type",
    "People ID From FB",
    "Update Source"
]]

df_people_relationships

,Lead ID,Relationship ID,Relationship First Name,Relationship Last Name,Relationship Type,Relationship Phone 1,Relationship Phone 1 - Type,Relationship Phone 2,Relationship Phone 2 - Type,Relationship Phone 3,...,Relationship Address 5 - Country,Relationship Address 5 - Type,Relationship Address 6 - Street,Relationship Address 6 - City,Relationship Address 6 - State,Relationship Address 6 - Zip,Relationship Address 6 - Country,Relationship Address 6 - Type,People ID From FB,Update Source
0,f51rh33n,f51rh33n-1,David,Hooker,,,,hkr_dv@yahoo.com,home,,...,,,,,,,,,732.0,Followup boss
1,l75me99v,l75me99v-1,Todd,Seay,,205640-6100,mobile,TSeay@metrobankpc.com,home,,...,,,,,,,,,731.0,Followup boss
2,z84mh14p,z84mh14p-1,Vicki Smith,,,205-283-4366,mobile,,,,...,,,,,,,,,730.0,Followup boss
3,a33vb62h,a33vb62h-1,Thomas,Webb,Co-op,2057908496,mobile,,,,...,,,,,,,,,729.0,Followup boss
4,x32ht82q,x32ht82q-1,Richard,Hicks,Spouse,2052599959,mobile,,,,...,,,,,,,,,728.0,Followup boss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,i74uu60v,i74uu60v-1,Kenny,,,2054419395,mobile,kennyjames169@yahoo.com,home,,...,,,,,,,,,28.0,Followup boss
458,e23la84w,e23la84w-1,Support,,,(855) 622-5311,work,support@followupboss.com,work,,...,,,,,,,,,2.0,Followup boss
459,e16569e7,e16569e7-1,Sales,,,(855) 888-9769,work,hi@followupboss.com,work,,...,,,,,,,,,1.0,Followup boss
460,cb7f094b,cb7f094b-1,Cindy L. Wilkins,,,,,,,,...,,,,,,,,,,App
461,r55ri47n,r55ri47n-1,Cindy L. Wilkins,,,,,,,,...,,,,,,,,,,App

In [59]:
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
from datetime import datetime as dt
import pytz

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("People Relationships")

sheet.clear()

data = [df_people_relationships.columns.values.tolist()] + df_people_relationships.values.tolist()

sheet.update(data)
print("Overwritten People Relationships")

Overwritten People Relationships

In [23]:
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
import numpy as np
import uuid
from datetime import datetime as dt
import pytz
from pymongo import MongoClient
from pymongoarrow.api import find_pandas_all

#run first the peoplerelationships.py

# Connect to MongoDB (adjust the connection string as needed)
client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_relationships']

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

# Example usage
df = get_all_data_as_dataframe()

# Connect to MongoDB
client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_relationships']

# Define the fields you want to extract
projection = {
    'id': 1,
    'firstName': 1,
    'lastName': 1,
    'type': 1,
    'phones.value': 1,
    'phones.type': 1,
    'emails.value': 1,
    'emails.type': 1,
    'addresses.street': 1,
    'addresses.city': 1,
    'addresses.state': 1,
    'addresses.code': 1,
    'addresses.country': 1,
    'addresses.type': 1
}

# Use find_pandas_all to query MongoDB and get a DataFrame
df = find_pandas_all(collection, {}, projection=projection)

# Limit the number of phones to 6
df['phones'] = df['phones'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['emails'] = df['emails'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['addresses'] = df['addresses'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])

# Create separate columns for the first 6 phones
for i in range(6):
    df[f'phone_{i+1}'] = df['phones'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'phone_type_{i+1}'] = df['phones'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'email_{i+1}'] = df['emails'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'email_type_{i+1}'] = df['emails'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'address_street_{i+1}'] = df['addresses'].apply(lambda x: x[i]['street'] if len(x) > i else None)
    df[f'address_city_{i+1}'] = df['addresses'].apply(lambda x: x[i]['city'] if len(x) > i else None)
    df[f'address_state_{i+1}'] = df['addresses'].apply(lambda x: x[i]['state'] if len(x) > i else None)
    df[f'address_code_{i+1}'] = df['addresses'].apply(lambda x: x[i]['code'] if len(x) > i else None)
    df[f'address_country_{i+1}'] = df['addresses'].apply(lambda x: x[i]['country'] if len(x) > i else None)
    df[f'address_type_{i+1}'] = df['addresses'].apply(lambda x: x[i]['type'] if len(x) > i else None)

# Drop the original 'phones' column if not needed
df.drop(columns=['phones'], inplace=True)
df.drop(columns=['emails'], inplace=True)
df.drop(columns=['addresses'], inplace=True)

# Display the DataFrame
df['Update Source'] = "Followup boss"
df.columns = [
    "Mongodb ID",
"People ID From FB",
"Relationship First Name",
"Relationship Last Name",
"Relationship Type",
"Relationship Phone 1",
"Relationship Phone 1 - Type",
"Relationship Phone 2",
"Relationship Phone 2 - Type",
"Relationship Phone 3",
"Relationship Phone 3 - Type",
"Relationship Phone 4",
"Relationship Phone 4 - Type",
"Relationship Phone 5",
"Relationship Phone 5 - Type",
"Relationship Phone 6",
"Relationship Phone 6 - Type",
"Relationship Email 1",
"Relationship Email 1 - Type",
"Relationship Email 2",
"Relationship Email 2 - Type",
"Relationship Email 3",
"Relationship Email 3 - Type",
"Relationship Email 4",
"Relationship Email 4 - Type",
"Relationship Email 5",
"Relationship Email 5 - Type",
"Relationship Email 6",
"Relationship Email 6 - Type",
"Relationship Address 1 - Street",
"Relationship Address 1 - City",
"Relationship Address 1 - State",
"Relationship Address 1 - Zip",
"Relationship Address 1 - Country",
"Relationship Address 1 - Type",
"Relationship Address 2 - Street",
"Relationship Address 2 - City",
"Relationship Address 2 - State",
"Relationship Address 2 - Zip",
"Relationship Address 2 - Country",
"Relationship Address 2 - Type",
"Relationship Address 3 - Street",
"Relationship Address 3 - City",
"Relationship Address 3 - State",
"Relationship Address 3 - Zip",
"Relationship Address 3 - Country",
"Relationship Address 3 - Type",
"Relationship Address 4 - Street",
"Relationship Address 4 - City",
"Relationship Address 4 - State",
"Relationship Address 4 - Zip",
"Relationship Address 4 - Country",
"Relationship Address 4 - Type",
"Relationship Address 5 - Street",
"Relationship Address 5 - City",
"Relationship Address 5 - State",
"Relationship Address 5 - Zip",
"Relationship Address 5 - Country",
"Relationship Address 5 - Type",
"Relationship Address 6 - Street",
"Relationship Address 6 - City",
"Relationship Address 6 - State",
"Relationship Address 6 - Zip",
"Relationship Address 6 - Country",
"Relationship Address 6 - Type",
"Update Source"
]

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")

# Get all data in the sheet
data = sheet.get_all_values()

# Convert the data into a pandas DataFrame
df_1 = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_1[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['People ID From FB'] = df['People ID From FB'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people relationships from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='People ID From FB', right_on='ID')
print(f'length of rows of people relationships from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new = df_new[[
    "Lead ID",
    "Relationship First Name",
    "Relationship Last Name",
    "Relationship Type",
    "Relationship Phone 1",
    "Relationship Phone 1 - Type",
    "Relationship Phone 2",
    "Relationship Phone 2 - Type",
    "Relationship Phone 3",
    "Relationship Phone 3 - Type",
    "Relationship Phone 4",
    "Relationship Phone 4 - Type",
    "Relationship Phone 5",
    "Relationship Phone 5 - Type",
    "Relationship Phone 6",
    "Relationship Phone 6 - Type",
    "Relationship Email 1",
    "Relationship Email 1 - Type",
    "Relationship Email 2",
    "Relationship Email 2 - Type",
    "Relationship Email 3",
    "Relationship Email 3 - Type",
    "Relationship Email 4",
    "Relationship Email 4 - Type",
    "Relationship Email 5",
    "Relationship Email 5 - Type",
    "Relationship Email 6",
    "Relationship Email 6 - Type",
    "Relationship Address 1 - Street",
    "Relationship Address 1 - City",
    "Relationship Address 1 - State",
    "Relationship Address 1 - Zip",
    "Relationship Address 1 - Country",
    "Relationship Address 1 - Type",
    "Relationship Address 2 - Street",
    "Relationship Address 2 - City",
    "Relationship Address 2 - State",
    "Relationship Address 2 - Zip",
    "Relationship Address 2 - Country",
    "Relationship Address 2 - Type",
    "Relationship Address 3 - Street",
    "Relationship Address 3 - City",
    "Relationship Address 3 - State",
    "Relationship Address 3 - Zip",
    "Relationship Address 3 - Country",
    "Relationship Address 3 - Type",
    "Relationship Address 4 - Street",
    "Relationship Address 4 - City",
    "Relationship Address 4 - State",
    "Relationship Address 4 - Zip",
    "Relationship Address 4 - Country",
    "Relationship Address 4 - Type",
    "Relationship Address 5 - Street",
    "Relationship Address 5 - City",
    "Relationship Address 5 - State",
    "Relationship Address 5 - Zip",
    "Relationship Address 5 - Country",
    "Relationship Address 5 - Type",
    "Relationship Address 6 - Street",
    "Relationship Address 6 - City",
    "Relationship Address 6 - State",
    "Relationship Address 6 - Zip",
    "Relationship Address 6 - Country",
    "Relationship Address 6 - Type",
    "People ID From FB",
    "Update Source"
]]

# Step 1: Group by 'Lead ID' and create a row number within each group
df_new['Row Number'] = df_new.groupby('Lead ID').cumcount() + 1

# Step 2: Concatenate 'Lead ID' with the row number to create 'Relationship ID'
df_new['Relationship ID'] = df_new['Lead ID'] + '-' + df_new['Row Number'].astype(str)
df_new.replace([np.inf, -np.inf, np.nan], '', inplace=True)

# Resulting DataFrame
df_from_fub = df_new[[
    "Lead ID",
    "Relationship ID",
    "Relationship First Name",
    "Relationship Last Name",
    "Relationship Type",
    "Relationship Phone 1",
    "Relationship Phone 1 - Type",
    "Relationship Phone 2",
    "Relationship Phone 2 - Type",
    "Relationship Phone 3",
    "Relationship Phone 3 - Type",
    "Relationship Phone 4",
    "Relationship Phone 4 - Type",
    "Relationship Phone 5",
    "Relationship Phone 5 - Type",
    "Relationship Phone 6",
    "Relationship Phone 6 - Type",
    "Relationship Email 1",
    "Relationship Email 1 - Type",
    "Relationship Email 2",
    "Relationship Email 2 - Type",
    "Relationship Email 3",
    "Relationship Email 3 - Type",
    "Relationship Email 4",
    "Relationship Email 4 - Type",
    "Relationship Email 5",
    "Relationship Email 5 - Type",
    "Relationship Email 6",
    "Relationship Email 6 - Type",
    "Relationship Address 1 - Street",
    "Relationship Address 1 - City",
    "Relationship Address 1 - State",
    "Relationship Address 1 - Zip",
    "Relationship Address 1 - Country",
    "Relationship Address 1 - Type",
    "Relationship Address 2 - Street",
    "Relationship Address 2 - City",
    "Relationship Address 2 - State",
    "Relationship Address 2 - Zip",
    "Relationship Address 2 - Country",
    "Relationship Address 2 - Type",
    "Relationship Address 3 - Street",
    "Relationship Address 3 - City",
    "Relationship Address 3 - State",
    "Relationship Address 3 - Zip",
    "Relationship Address 3 - Country",
    "Relationship Address 3 - Type",
    "Relationship Address 4 - Street",
    "Relationship Address 4 - City",
    "Relationship Address 4 - State",
    "Relationship Address 4 - Zip",
    "Relationship Address 4 - Country",
    "Relationship Address 4 - Type",
    "Relationship Address 5 - Street",
    "Relationship Address 5 - City",
    "Relationship Address 5 - State",
    "Relationship Address 5 - Zip",
    "Relationship Address 5 - Country",
    "Relationship Address 5 - Type",
    "Relationship Address 6 - Street",
    "Relationship Address 6 - City",
    "Relationship Address 6 - State",
    "Relationship Address 6 - Zip",
    "Relationship Address 6 - Country",
    "Relationship Address 6 - Type",
    "People ID From FB",
    "Update Source"
]]

client = MongoClient()
db = client['Christina']
collection = db['app_people_relationships']

initial_count_of_collection = collection.count_documents({})

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_documents():
    # print(f"There are {collection.count_documents({})} documents now in {collection.name}")
    return collection.count_documents({})

delete_all()

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("People Relationships")

# Get all data in the sheet
data = sheet.get_all_values()

headers = data[0]
rows = data[1:]

documents = [dict(zip(headers, row)) for row in rows]

if documents:
    collection.insert_many(documents)
    print("Data successfully inserted to Mongodb")
else:
    print("No data to insert.")

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

df_app = get_all_data_as_dataframe()
df_app = df_app[df_app['Update Source'] == "App"]

df_final = pd.concat([df_from_fub, df_app], ignore_index=True)

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Copy of People Relationships")

sheet.clear()

df_final = df_final.replace('', None)
# df_final = df_final.replace([np.inf, -np.inf], np.nan).fillna(np.nan)
df_final.drop('_id', axis=1, inplace=True)

data = [df_final.columns.values.tolist()] + df_final.values.tolist()

sheet.update(data)
print("Overwritten People Relationships")

C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_17152\1264808270.py:169: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_17152\1264808270.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_17152\1264808270.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id.dropna(subset=['ID'], inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_17152\1264808270.py:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'] = unique_people_id['ID'].astype(int)

length of rows of people relationships from followup boss before merge: 460
length of rows of people relationships from followup boss after merge: 460
Deleted 469 documents from app_people_relationships
Data successfully inserted to Mongodb
Overwritten People Relationships

In [24]:
from datetime import datetime as dt
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from pymongo import MongoClient

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nPeople Extract Start time in USA: {current_time_initial}')
    file.write(f'\nPeople Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
total = data["_metadata"]["total"]

client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_backup']

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_collections():
    print(f"There are {collection.count_documents({})} documents now in {collection.name}")
    
delete_all()

list_of_offsets = list(range(0, round(total, -2) + 1, 100))
date_now = dt.today().strftime('%m/%d/%Y')

for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
    url = f'https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset={i}&includeTrash=false&includeUnclaimed=false'
    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['people']:
        if isinstance(x, dict):
            insert_one_document(x)
            
count_of_all_collections()

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nAdded {count_of_all_collections()} in the collection {collection}')
    file.write(f'\nPeople Extract End time in USA: {current_time}')
    file.write(f'\nPeople Extract End time in PH: {current_time_ph}\n')
    file.write(f'\nPeople Total Running time: {total_running_time}')

Deleted 0 documents from followupboss_people_backup

Processing People from Followup boss: 100%|██████████| 64/64 [01:22<00:00,  1.29s/it]

There are 6292 documents now in followupboss_people_backup
There are 6292 documents now in followupboss_people_backup

In [25]:
def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

# Example usage
df = get_all_data_as_dataframe()
df

,_id,id,created,updated,createdVia,lastActivity,name,firstName,lastName,stage,...,claimed,dealStatus,dealStage,dealName,dealCloseDate,dealPrice,firstToClaimOffer,collaborators,teamLeaders,pondMembers
0,67150c7ae137b38469709061,8739,2023-06-20T19:11:58Z,2023-06-20T20:50:23Z,Manually,2023-06-20T20:50:23Z,Follow Up Boss Customer Service,Follow Up Boss,Customer Service,Vendors,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
1,67150c7ae137b38469709062,10445,2023-06-21T18:28:02Z,2023-06-21T18:32:19Z,Manually,2023-06-21T23:37:30Z,Matria Chapple,Matria,Chapple,Referral Partners,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
2,67150c7ae137b38469709063,12213,2023-07-24T20:22:40Z,2023-07-24T20:23:31Z,Manually,2023-07-24T20:25:09Z,Bianca Villalta,Bianca,Villalta,Vendors,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
3,67150c7ae137b38469709064,12212,2023-07-24T20:21:21Z,2023-07-25T15:43:37Z,Manually,2023-07-25T15:43:37Z,Sasha Geotrarget,Sasha,Geotrarget,Vendors,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
4,67150c7ae137b38469709065,8711,2023-06-14T16:15:36Z,2023-07-26T16:56:34Z,Email Parsing,2023-07-26T16:56:34Z,Krish,Krish,,Contact,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6287,67150ccbe137b3846970a8f0,8526,2021-08-13T22:30:00Z,2024-07-11T20:21:33Z,Import,2024-10-19T20:50:52Z,Brandon Speight,Brandon,Speight,B - Warm 3-6 Months,...,True,None,None,None,None,NaN,False,"[{'id': 7, 'name': 'Jaki Ahlemeyer', 'assigned...",[],[]
6288,67150ccbe137b3846970a8f1,5530,2020-02-07T06:10:00Z,2024-10-13T09:41:18Z,Import,2024-10-19T21:13:40Z,Jerry & Gayle Carder,Jerry & Gayle,Carder,B - Warm 3-6 Months,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
6289,67150ccbe137b3846970a8f2,13305,2024-10-20T01:00:05Z,2024-10-20T01:00:10Z,API,2024-10-20T01:01:55Z,Sue Johnson,Sue,Johnson,Lead,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
6290,67150ccbe137b3846970a8f3,14,2023-05-12T04:22:08Z,2024-10-20T11:25:41Z,Historic Email Parsing,2024-10-20T11:25:41Z,Betta Horn,Betta,Horn,Contact,...,True,None,None,None,None,NaN,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]
6291,67150ccbe137b3846970a8f4,583,2023-05-24T18:09:36Z,2024-10-01T14:06:59Z,API,2024-10-20T13:17:15Z,Christina James,Christina,James,C - Cold 6-12 Months,...,True,Active,Buyers - 2022 Closed Deals,3041 Lorna Rd,2022-06-29 05:00:00,598000.0,False,"[{'id': 1, 'name': 'Christina James', 'assigne...",[],[]

In [27]:
df.columns

Index(['_id', 'id', 'created', 'updated', 'createdVia', 'lastActivity', 'name',
       'firstName', 'lastName', 'stage', 'stageId', 'source', 'sourceId',
       'sourceUrl', 'leadFlowId', 'delayed', 'contacted', 'price',
       'assignedLenderId', 'assignedLenderName', 'assignedUserId',
       'assignedPondId', 'assignedTo', 'tags', 'emails', 'phones', 'addresses',
       'picture', 'socialData', 'websiteVisits', 'timeframeId',
       'timeframeUpdated', 'timeframeStatus', 'claimed', 'dealStatus',
       'dealStage', 'dealName', 'dealCloseDate', 'dealPrice',
       'firstToClaimOffer', 'collaborators', 'teamLeaders', 'pondMembers'],
      dtype='object')

In [26]:
# list(df.columns)

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")

# Get all data in the sheet
data = sheet.get_all_values()

# Convert the data into a pandas DataFrame
df_leads = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_leads[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['id'] = df['id'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people relationships from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='People ID From FB', right_on='ID')
print(f'length of rows of people relationships from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new.replace([np.inf, -np.inf, np.nan], None, inplace=True)
# df_new = df_new[[
#     "Lead ID",
#     "Relationship First Name",

['_id',
 'id',
 'created',
 'updated',
 'createdVia',
 'lastActivity',
 'name',
 'firstName',
 'lastName',
 'stage',
 'stageId',
 'source',
 'sourceId',
 'sourceUrl',
 'leadFlowId',
 'delayed',
 'contacted',
 'price',
 'assignedLenderId',
 'assignedLenderName',
 'assignedUserId',
 'assignedPondId',
 'assignedTo',
 'tags',
 'emails',
 'phones',
 'addresses',
 'picture',
 'socialData',
 'websiteVisits',
 'timeframeId',
 'timeframeUpdated',
 'timeframeStatus',
 'claimed',
 'dealStatus',
 'dealStage',
 'dealName',
 'dealCloseDate',
 'dealPrice',
 'firstToClaimOffer',
 'collaborators',
 'teamLeaders',
 'pondMembers']

In [17]:
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from datetime import datetime as dt
import pytz
import winsound

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nCalls Extract Start time in USA: {current_time_initial}')
    file.write(f'\nCalls Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

from pymongo import MongoClient
client = MongoClient()
db = client['Christina']
collection = db['followupboss_calls']

initial_count_of_collection = collection.count_documents({})

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_documents():
    # print(f"There are {collection.count_documents({})} documents now in {collection.name}")
    return collection.count_documents({})

delete_all()

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/calls?limit=100&offset=0"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
with open(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\calls.json', 'w') as file:
    json.dump(data, file, indent=4)
    
total = round(data['_metadata']['total'] / 100, None)
# list_of_offsets = list(range(0, round(total, -1) + 1, 100))
nextLink = data['_metadata']['nextLink']
for x in data['calls']:
    if isinstance(x, dict):
        insert_one_document(x)

counter = 0
with tqdm(total, total=total, desc="Extracting calls", leave=True) as pbar:
    while nextLink:
    # for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
        # url = f"https://api.followupboss.com/v1/calls?limit=100&offset={i}"

        r = requests.get(nextLink, headers={'accept': "application/json",
                                    'Authorization': "Basic " + encoded_api_key,
                                        'X-System-Key': X_System_Key,
                                        'X-System': X_System
        })
        if r.status_code == 200:
            data = r.json()
            nextLink = data['_metadata'].get('nextLink')
            for x in data.get('calls', []):
                if isinstance(x, dict):
                    insert_one_document(x)
            pbar.update(1)
        else:
            print(f'Failed to fetch data. Status code: {r.status_code}')
            nextLink = None

final_count_of_collection = count_of_all_documents() - initial_count_of_collection
print(f'Added {final_count_of_collection} in the collection {collection.name}')
print(f'Total Number of documents: {count_of_all_documents()} in the collection {collection}')
# Beep at frequency 1000 Hz for 500 milliseconds
winsound.Beep(1000, 500)

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nTotal Number of documents: {count_of_all_documents()} in the collection {collection.name}')
    file.write(f'\nCalls Extract End time in USA: {current_time}')
    file.write(f'\nCalls Extract End time in PH: {current_time_ph}\n')
    file.write(f'\nCalls Total Running time: {total_running_time}')

Deleted 100 documents from followupboss_calls

Extracting calls: 100%|█████████▉| 279/280 [06:18<00:01,  1.36s/it]

Added 27890 in the collection followupboss_calls
Total Number of documents: 27990 in the collection Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'Christina'), 'followupboss_calls')

In [95]:
from datetime import datetime as dt
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from pymongo import MongoClient
import gspread
from google.oauth2.service_account import Credentials
import uuid
import numpy as np

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nPeople Extract Start time in USA: {current_time_initial}')
    file.write(f'\nPeople Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
total = data["_metadata"]["total"]

client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_backup']

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_collections():
    return collection.count_documents({})    

initial_count = count_of_all_collections()
print(f"There are {initial_count} documents now in {collection.name}")

delete_all()

list_of_offsets = list(range(0, round(total, -2) + 1, 100))
date_now = dt.today().strftime('%m/%d/%Y')

for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
    url = f'https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset={i}&includeTrash=false&includeUnclaimed=false'
    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['people']:
        if isinstance(x, dict):
            insert_one_document(x)

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

final_count = count_of_all_collections() - initial_count
print(f"There are {final_count} documents now in {collection.name}")

with open(logfile, 'a') as file:
    file.write(f"There are {count_of_all_collections()} documents now in {collection.name}")
    file.write(f'\nAdded {final_count} in the collection {collection.name}')
    file.write(f'\nPeople Extract End time in USA: {current_time}')
    file.write(f'\nPeople Extract End time in PH: {current_time_ph}\n')
    file.write(f'\nPeople Total Running time: {total_running_time}')

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

df = get_all_data_as_dataframe()

# Limit the number of phones to 6
df['phones'] = df['phones'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['emails'] = df['emails'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['addresses'] = df['addresses'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])

# Create separate columns for the first 6 phones
for i in range(6):
    df[f'phone_{i+1}'] = df['phones'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'phone_type_{i+1}'] = df['phones'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'email_{i+1}'] = df['emails'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'email_type_{i+1}'] = df['emails'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'address_street_{i+1}'] = df['addresses'].apply(lambda x: x[i]['street'] if len(x) > i else None)
    df[f'address_city_{i+1}'] = df['addresses'].apply(lambda x: x[i]['city'] if len(x) > i else None)
    df[f'address_state_{i+1}'] = df['addresses'].apply(lambda x: x[i]['state'] if len(x) > i else None)
    df[f'address_code_{i+1}'] = df['addresses'].apply(lambda x: x[i]['code'] if len(x) > i else None)
    df[f'address_country_{i+1}'] = df['addresses'].apply(lambda x: x[i]['country'] if len(x) > i else None)
    df[f'address_type_{i+1}'] = df['addresses'].apply(lambda x: x[i]['type'] if len(x) > i else None)

# Drop the original 'phones' column if not needed
df.drop(columns=['phones'], inplace=True)
df.drop(columns=['emails'], inplace=True)
df.drop(columns=['addresses'], inplace=True)

# Display the DataFrame
df['Update Source'] = "Followup boss"

SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)
client = gspread.authorize(creds)
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")
data = sheet.get_all_values()
df_leads = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_leads[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['id'] = df['id'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='id', right_on='ID')
print(f'length of rows of people from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new.replace([np.inf, -np.inf, np.nan], None, inplace=True)

df_new['Budget'] = df_new['price']

df_app_only = df_leads[df_leads['Update Source'] == 'App']

df_fub_only = df_new[~df_new['Lead ID'].isin(df_app_only['Lead ID'])]
df_fub_only['Update Source'] = 'Followup boss'
# df_fub_only2 = df_fub_only.copy()
# df_fub_only = df_fub_only2.copy()

df_fub_only['Lead ID'] = df_fub_only['Lead ID']
df_fub_only['Year'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%Y')
df_fub_only['Month'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%b')
df_fub_only['Agent ID'] = df_fub_only['assignedUserId']
df_fub_only['Date Added'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%m-%d-%Y')
df_fub_only['Name'] = df_fub_only['name']
df_fub_only['First Name'] = df_fub_only['firstName']
df_fub_only['Last Name'] = df_fub_only['lastName']
df_fub_only['Stage'] = df_fub_only['stage']
df_fub_only['Lead Source'] = df_fub_only['source']
df_fub_only['Assigned To'] = df_fub_only['assignedTo']
df_fub_only['Last Assigned'] = df_fub_only['updated']
df_fub_only['Is Contacted'] = pd.to_datetime(df_fub_only['contacted']).dt.strftime('%m-%d-%Y')
df_fub_only['Listing Price'] = pd.to_datetime(df_fub_only['price']).dt.strftime('%m-%d-%Y')
df_fub_only['Tags'] = df_fub_only['tags']
df_fub_only['Email 1'] = df_fub_only['email_1']
df_fub_only['Email 1 - Type'] = df_fub_only['email_type_1']
df_fub_only['Email 2'] = df_fub_only['email_2']
df_fub_only['Email 2 - Type'] = df_fub_only['email_type_2']
df_fub_only['Email 3'] = df_fub_only['email_3']
df_fub_only['Email 3 - Type'] = df_fub_only['email_type_3']
df_fub_only['Email 4'] = df_fub_only['email_4']
df_fub_only['Email 4 - Type'] = df_fub_only['email_type_4']
df_fub_only['Email 5'] = df_fub_only['email_5']
df_fub_only['Email 5 - Type'] = df_fub_only['email_type_5']
df_fub_only['Email 6'] = df_fub_only['email_6']
df_fub_only['Email 6 - Type'] = df_fub_only['email_type_6']
df_fub_only['Phone 1'] = df_fub_only['phone_1']
df_fub_only['Phone 1 - Type'] = df_fub_only['phone_type_1']
df_fub_only['Phone 2'] = df_fub_only['phone_2']
df_fub_only['Phone 2 - Type'] = df_fub_only['phone_type_2']
df_fub_only['Phone 3'] = df_fub_only['phone_3']
df_fub_only['Phone 3 - Type'] = df_fub_only['phone_type_3']
df_fub_only['Phone 4'] = df_fub_only['phone_4']
df_fub_only['Phone 4 - Type'] = df_fub_only['phone_type_4']
df_fub_only['Phone 5'] = df_fub_only['phone_5']
df_fub_only['Phone 5 - Type'] = df_fub_only['phone_type_5']
df_fub_only['Phone 6'] = df_fub_only['phone_6']
df_fub_only['Phone 6 - Type'] = df_fub_only['phone_type_6']
df_fub_only['Address 1 - Street'] = df_fub_only['address_street_1']
df_fub_only['Address 1 - City'] = df_fub_only['address_city_1']
df_fub_only['Address 1 - State'] = df_fub_only['address_state_1']
df_fub_only['Address 1 - Zip'] = df_fub_only['address_code_1']
df_fub_only['Address 1 - Country'] = df_fub_only['address_country_1']
df_fub_only['Address 1 - Type'] = df_fub_only['address_type_1']
df_fub_only['Address 2 - Street'] = df_fub_only['address_street_2']
df_fub_only['Address 2 - City'] = df_fub_only['address_city_2']
df_fub_only['Address 2 - State'] = df_fub_only['address_state_2']
df_fub_only['Address 2 - Zip'] = df_fub_only['address_code_2']
df_fub_only['Address 2 - Country'] = df_fub_only['address_country_2']
df_fub_only['Address 2 - Type'] = df_fub_only['address_type_2']
df_fub_only['Address 3 - Street'] = df_fub_only['address_street_3']
df_fub_only['Address 3 - City'] = df_fub_only['address_city_3']
df_fub_only['Address 3 - State'] = df_fub_only['address_state_3']
df_fub_only['Address 3 - Zip'] = df_fub_only['address_code_3']
df_fub_only['Address 3 - Country'] = df_fub_only['address_country_3']
df_fub_only['Address 3 - Type'] = df_fub_only['address_type_3']
df_fub_only['Address 4 - Street'] = df_fub_only['address_street_4']
df_fub_only['Address 4 - City'] = df_fub_only['address_city_4']
df_fub_only['Address 4 - State'] = df_fub_only['address_state_4']
df_fub_only['Address 4 - Zip'] = df_fub_only['address_code_4']
df_fub_only['Address 4 - Country'] = df_fub_only['address_country_4']
df_fub_only['Address 4 - Type'] = df_fub_only['address_type_4']
df_fub_only['Address 5 - Street'] = df_fub_only['address_street_5']
df_fub_only['Address 5 - City'] = df_fub_only['address_city_5']
df_fub_only['Address 5 - State'] = df_fub_only['address_state_5']
df_fub_only['Address 5 - Zip'] = df_fub_only['address_code_5']
df_fub_only['Address 5 - Country'] = df_fub_only['address_country_5']
df_fub_only['Address 5 - Type'] = df_fub_only['address_type_5']
df_fub_only['Address 6 - Street'] = df_fub_only['address_street_6']
df_fub_only['Address 6 - City'] = df_fub_only['address_city_6']
df_fub_only['Address 6 - State'] = df_fub_only['address_state_6']
df_fub_only['Address 6 - Zip'] = df_fub_only['address_code_6']
df_fub_only['Address 6 - Country'] = df_fub_only['address_country_6']
df_fub_only['Address 6 - Type'] = df_fub_only['address_type_6']
df_fub_only['Property Address'] = None
df_fub_only['Property City'] = None
df_fub_only['Property State'] = None
df_fub_only['Property Postal Code'] = None
df_fub_only['Property MLS Number'] = None
df_fub_only['Property Price'] = None
df_fub_only['Property Beds'] = None
df_fub_only['Property Baths'] = None
df_fub_only['Property Area'] = None
df_fub_only['Property Lot'] = None
df_fub_only['Message'] = None
df_fub_only['Description'] = None
df_fub_only['Notes'] = None
df_fub_only['Calls'] = None
df_fub_only['Texts'] = None
df_fub_only['Background'] = None
df_fub_only['Campaign Source'] = None
df_fub_only['Campaign Medium'] = None
df_fub_only['Campaign Term'] = None
df_fub_only['Campaign Content'] = None
df_fub_only['Campaign Name'] = None
df_fub_only['Deal Stage'] = df_fub_only['dealStage']
df_fub_only['Deal Close Date'] = df_fub_only['dealCloseDate']
df_fub_only['Deal Price'] = df_fub_only['dealPrice']
df_fub_only['ID'] = df_fub_only['id']
df_fub_only['Birthday'] = None
df_fub_only['Closing Anniversary'] = None
df_fub_only['Date Reassigned'] = None
df_fub_only['Home Anniversary'] = None
df_fub_only['Huddle URL'] = None
df_fub_only['RealGeeks URL'] = None
df_fub_only['Timeframe'] = None
df_fub_only['Website'] = None
df_fub_only['Update Source'] = None
df_fub_only['Budget'] = df_fub_only['price']

df_fub_only = df_fub_only[[
    'Lead ID',
    'Year',
    'Month',
    'Agent ID',
    'Date Added',
    'Name',
    'First Name',
    'Last Name',
    'Stage',
    'Lead Source',
    'Assigned To',
    'Last Assigned',
    'Is Contacted',
    'Listing Price',
    'Tags',
    'Email 1',
    'Email 1 - Type',
    'Email 2',
    'Email 2 - Type',
    'Email 3',
    'Email 3 - Type',
    'Email 4',
    'Email 4 - Type',
    'Email 5',
    'Email 5 - Type',
    'Email 6',
    'Email 6 - Type',
    'Phone 1',
    'Phone 1 - Type',
    'Phone 2',
    'Phone 2 - Type',
    'Phone 3',
    'Phone 3 - Type',
    'Phone 4',
    'Phone 4 - Type',
    'Phone 5',
    'Phone 5 - Type',
    'Phone 6',
    'Phone 6 - Type',
    'Address 1 - Street',
    'Address 1 - City',
    'Address 1 - State',
    'Address 1 - Zip',
    'Address 1 - Country',
    'Address 1 - Type',
    'Address 2 - Street',
    'Address 2 - City',
    'Address 2 - State',
    'Address 2 - Zip',
    'Address 2 - Country',
    'Address 2 - Type',
    'Address 3 - Street',
    'Address 3 - City',
    'Address 3 - State',
    'Address 3 - Zip',
    'Address 3 - Country',
    'Address 3 - Type',
    'Address 4 - Street',
    'Address 4 - City',
    'Address 4 - State',
    'Address 4 - Zip',
    'Address 4 - Country',
    'Address 4 - Type',
    'Address 5 - Street',
    'Address 5 - City',
    'Address 5 - State',
    'Address 5 - Zip',
    'Address 5 - Country',
    'Address 5 - Type',
    'Address 6 - Street',
    'Address 6 - City',
    'Address 6 - State',
    'Address 6 - Zip',
    'Address 6 - Country',
    'Address 6 - Type',
    'Property Address',
    'Property City',
    'Property State',
    'Property Postal Code',
    'Property MLS Number',
    'Property Price',
    'Property Beds',
    'Property Baths',
    'Property Area',
    'Property Lot',
    'Message',
    'Description',
    'Notes',
    'Calls',
    'Texts',
    'Background',
    'Campaign Source',
    'Campaign Medium',
    'Campaign Term',
    'Campaign Content',
    'Campaign Name',
    'Deal Stage',
    'Deal Close Date',
    'Deal Price',
    'ID',
    'Birthday',
    'Closing Anniversary',
    'Date Reassigned',
    'Home Anniversary',
    'Huddle URL',
    'RealGeeks URL',
    'Timeframe',
    'Website',
    'Update Source',
    'Budget'
]]

# df_app_only.reset_index(inplace=True)

df_final = pd.concat([df_fub_only, df_app_only], ignore_index=True)
df_final.drop(['index'], axis=1, inplace=True)

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Copy of Leads 2")

sheet.clear()

# df_final = df_final.replace('', None)
df_final = df_final.replace([np.inf, -np.inf, '', np.nan], None)
# df_final = df_final.replace([np.inf, -np.inf, ''], np.nan).fillna(None)
# df_final.drop('_id', axis=1, inplace=True)

# data = [df_final.columns.values.tolist()] + df_final.values.tolist()
data = [df_final.columns.values.tolist()] + df_final.astype(str).values.tolist()


sheet.update(data)
print("Overwritten Leads")

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nTotal Number of leads: {len(df_final)} in the collection {collection.name}')
    file.write(f'\nUpdate Leads Gsheet End time in USA: {current_time}')
    file.write(f'\nUpdate Leads Gsheet End time in PH: {current_time_ph}\n')
    file.write(f'\nUpdate Leads Gsheet Total Running time: {total_running_time}')

There are 6299 documents now in followupboss_people_backup
Deleted 6299 documents from followupboss_people_backup

Processing People from Followup boss: 100%|██████████| 64/64 [01:19<00:00,  1.24s/it]

There are 0 documents now in followupboss_people_backup
length of rows of people from followup boss before merge: 6299
length of rows of people from followup boss after merge: 6299

C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\3933340944.py:139: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\3933340944.py:139: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\3933340944.py:140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id.dropna(subset=['ID'], inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\3933340944.py:143: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'] = unique_people_id['ID'].astype(int)

In [131]:
from datetime import datetime as dt
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from pymongo import MongoClient
import gspread
from google.oauth2.service_account import Credentials
import uuid
import numpy as np

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nPeople Extract Start time in USA: {current_time_initial}')
    file.write(f'\nPeople Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
total = data["_metadata"]["total"]

client = MongoClient()
db = client['Christina']
collection = db['followupboss_people_backup']

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_collections():
    return collection.count_documents({})    

initial_count = count_of_all_collections()
print(f"There are {initial_count} documents now in {collection.name}")

delete_all()

list_of_offsets = list(range(0, round(total, -2) + 1, 100))
date_now = dt.today().strftime('%m/%d/%Y')

for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
    url = f'https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset={i}&includeTrash=false&includeUnclaimed=false'
    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['people']:
        if isinstance(x, dict):
            insert_one_document(x)

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

df = get_all_data_as_dataframe()

# Limit the number of phones to 6
df['phones'] = df['phones'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['emails'] = df['emails'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['addresses'] = df['addresses'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])

# Create separate columns for the first 6 phones
for i in range(6):
    df[f'phone_{i+1}'] = df['phones'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'phone_type_{i+1}'] = df['phones'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'email_{i+1}'] = df['emails'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'email_type_{i+1}'] = df['emails'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'address_street_{i+1}'] = df['addresses'].apply(lambda x: x[i]['street'] if len(x) > i else None)
    df[f'address_city_{i+1}'] = df['addresses'].apply(lambda x: x[i]['city'] if len(x) > i else None)
    df[f'address_state_{i+1}'] = df['addresses'].apply(lambda x: x[i]['state'] if len(x) > i else None)
    df[f'address_code_{i+1}'] = df['addresses'].apply(lambda x: x[i]['code'] if len(x) > i else None)
    df[f'address_country_{i+1}'] = df['addresses'].apply(lambda x: x[i]['country'] if len(x) > i else None)
    df[f'address_type_{i+1}'] = df['addresses'].apply(lambda x: x[i]['type'] if len(x) > i else None)

# Drop the original 'phones' column if not needed
df.drop(columns=['phones'], inplace=True)
df.drop(columns=['emails'], inplace=True)
df.drop(columns=['addresses'], inplace=True)

# Display the DataFrame
df['Update Source'] = "Followup boss"

SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)
client = gspread.authorize(creds)
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")
data = sheet.get_all_values()
df_leads = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_leads[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['id'] = df['id'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='id', right_on='ID')
print(f'length of rows of people from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new.replace([np.inf, -np.inf, np.nan], None, inplace=True)

df_new['Budget'] = df_new['price']

df_app_only = df_leads[df_leads['Update Source'] == 'App']

df_fub_only = df_new[~df_new['Lead ID'].isin(df_app_only['Lead ID'])]
df_fub_only['Update Source'] = 'Followup boss'
# df_fub_only2 = df_fub_only.copy()
# df_fub_only = df_fub_only2.copy()

df_fub_only['Lead ID'] = df_fub_only['Lead ID']
df_fub_only['Year'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%Y')
df_fub_only['Month'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%b')
df_fub_only['Agent ID'] = df_fub_only['assignedUserId']
df_fub_only['Date Added'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%m-%d-%Y')
df_fub_only['Name'] = df_fub_only['firstName'] + ' ' + df_fub_only['lastName']
df_fub_only['First Name'] = df_fub_only['firstName']
df_fub_only['Last Name'] = df_fub_only['lastName']
df_fub_only['Stage'] = df_fub_only['stage']
df_fub_only['Lead Source'] = df_fub_only['source']
df_fub_only['Assigned To'] = df_fub_only['assignedTo']
df_fub_only['Last Assigned'] = df_fub_only['updated']
df_fub_only['Is Contacted'] = pd.to_datetime(df_fub_only['contacted']).dt.strftime('%m-%d-%Y')
df_fub_only['Listing Price'] = pd.to_datetime(df_fub_only['price']).dt.strftime('%m-%d-%Y')
df_fub_only['Tags'] = df_fub_only['tags']
df_fub_only['Email 1'] = df_fub_only['email_1']
df_fub_only['Email 1 - Type'] = df_fub_only['email_type_1']
df_fub_only['Email 2'] = df_fub_only['email_2']
df_fub_only['Email 2 - Type'] = df_fub_only['email_type_2']
df_fub_only['Email 3'] = df_fub_only['email_3']
df_fub_only['Email 3 - Type'] = df_fub_only['email_type_3']
df_fub_only['Email 4'] = df_fub_only['email_4']
df_fub_only['Email 4 - Type'] = df_fub_only['email_type_4']
df_fub_only['Email 5'] = df_fub_only['email_5']
df_fub_only['Email 5 - Type'] = df_fub_only['email_type_5']
df_fub_only['Email 6'] = df_fub_only['email_6']
df_fub_only['Email 6 - Type'] = df_fub_only['email_type_6']
df_fub_only['Phone 1'] = df_fub_only['phone_1']
df_fub_only['Phone 1 - Type'] = df_fub_only['phone_type_1']
df_fub_only['Phone 2'] = df_fub_only['phone_2']
df_fub_only['Phone 2 - Type'] = df_fub_only['phone_type_2']
df_fub_only['Phone 3'] = df_fub_only['phone_3']
df_fub_only['Phone 3 - Type'] = df_fub_only['phone_type_3']
df_fub_only['Phone 4'] = df_fub_only['phone_4']
df_fub_only['Phone 4 - Type'] = df_fub_only['phone_type_4']
df_fub_only['Phone 5'] = df_fub_only['phone_5']
df_fub_only['Phone 5 - Type'] = df_fub_only['phone_type_5']
df_fub_only['Phone 6'] = df_fub_only['phone_6']
df_fub_only['Phone 6 - Type'] = df_fub_only['phone_type_6']
df_fub_only['Address 1 - Street'] = df_fub_only['address_street_1']
df_fub_only['Address 1 - City'] = df_fub_only['address_city_1']
df_fub_only['Address 1 - State'] = df_fub_only['address_state_1']
df_fub_only['Address 1 - Zip'] = df_fub_only['address_code_1']
df_fub_only['Address 1 - Country'] = df_fub_only['address_country_1']
df_fub_only['Address 1 - Type'] = df_fub_only['address_type_1']
df_fub_only['Address 2 - Street'] = df_fub_only['address_street_2']
df_fub_only['Address 2 - City'] = df_fub_only['address_city_2']
df_fub_only['Address 2 - State'] = df_fub_only['address_state_2']
df_fub_only['Address 2 - Zip'] = df_fub_only['address_code_2']
df_fub_only['Address 2 - Country'] = df_fub_only['address_country_2']
df_fub_only['Address 2 - Type'] = df_fub_only['address_type_2']
df_fub_only['Address 3 - Street'] = df_fub_only['address_street_3']
df_fub_only['Address 3 - City'] = df_fub_only['address_city_3']
df_fub_only['Address 3 - State'] = df_fub_only['address_state_3']
df_fub_only['Address 3 - Zip'] = df_fub_only['address_code_3']
df_fub_only['Address 3 - Country'] = df_fub_only['address_country_3']
df_fub_only['Address 3 - Type'] = df_fub_only['address_type_3']
df_fub_only['Address 4 - Street'] = df_fub_only['address_street_4']
df_fub_only['Address 4 - City'] = df_fub_only['address_city_4']
df_fub_only['Address 4 - State'] = df_fub_only['address_state_4']
df_fub_only['Address 4 - Zip'] = df_fub_only['address_code_4']
df_fub_only['Address 4 - Country'] = df_fub_only['address_country_4']
df_fub_only['Address 4 - Type'] = df_fub_only['address_type_4']
df_fub_only['Address 5 - Street'] = df_fub_only['address_street_5']
df_fub_only['Address 5 - City'] = df_fub_only['address_city_5']
df_fub_only['Address 5 - State'] = df_fub_only['address_state_5']
df_fub_only['Address 5 - Zip'] = df_fub_only['address_code_5']
df_fub_only['Address 5 - Country'] = df_fub_only['address_country_5']
df_fub_only['Address 5 - Type'] = df_fub_only['address_type_5']
df_fub_only['Address 6 - Street'] = df_fub_only['address_street_6']
df_fub_only['Address 6 - City'] = df_fub_only['address_city_6']
df_fub_only['Address 6 - State'] = df_fub_only['address_state_6']
df_fub_only['Address 6 - Zip'] = df_fub_only['address_code_6']
df_fub_only['Address 6 - Country'] = df_fub_only['address_country_6']
df_fub_only['Address 6 - Type'] = df_fub_only['address_type_6']
df_fub_only['Property Address'] = None
df_fub_only['Property City'] = None
df_fub_only['Property State'] = None
df_fub_only['Property Postal Code'] = None
df_fub_only['Property MLS Number'] = None
df_fub_only['Property Price'] = None
df_fub_only['Property Beds'] = None
df_fub_only['Property Baths'] = None
df_fub_only['Property Area'] = None
df_fub_only['Property Lot'] = None
df_fub_only['Message'] = None
df_fub_only['Description'] = None
df_fub_only['Notes'] = None
df_fub_only['Calls'] = None
df_fub_only['Texts'] = None
df_fub_only['Background'] = None
df_fub_only['Campaign Source'] = None
df_fub_only['Campaign Medium'] = None
df_fub_only['Campaign Term'] = None
df_fub_only['Campaign Content'] = None
df_fub_only['Campaign Name'] = None
df_fub_only['Deal Stage'] = df_fub_only['dealStage']
df_fub_only['Deal Close Date'] = df_fub_only['dealCloseDate']
df_fub_only['Deal Price'] = df_fub_only['dealPrice']
df_fub_only['ID'] = df_fub_only['id']
df_fub_only['Birthday'] = None
df_fub_only['Closing Anniversary'] = None
df_fub_only['Date Reassigned'] = None
df_fub_only['Home Anniversary'] = None
df_fub_only['Huddle URL'] = None
df_fub_only['RealGeeks URL'] = None
df_fub_only['Timeframe'] = None
df_fub_only['Website'] = None
df_fub_only['Update Source'] = df_fub_only['Update Source']
df_fub_only['Budget'] = df_fub_only['price']

df_fub_only = df_fub_only[[
    'Lead ID',
    'Year',
    'Month',
    'Agent ID',
    'Date Added',
    'Name',
    'First Name',
    'Last Name',
    'Stage',
    'Lead Source',
    'Assigned To',
    'Last Assigned',
    'Is Contacted',
    'Listing Price',
    'Tags',
    'Email 1',
    'Email 1 - Type',
    'Email 2',
    'Email 2 - Type',
    'Email 3',
    'Email 3 - Type',
    'Email 4',
    'Email 4 - Type',
    'Email 5',
    'Email 5 - Type',
    'Email 6',
    'Email 6 - Type',
    'Phone 1',
    'Phone 1 - Type',
    'Phone 2',
    'Phone 2 - Type',
    'Phone 3',
    'Phone 3 - Type',
    'Phone 4',
    'Phone 4 - Type',
    'Phone 5',
    'Phone 5 - Type',
    'Phone 6',
    'Phone 6 - Type',
    'Address 1 - Street',
    'Address 1 - City',
    'Address 1 - State',
    'Address 1 - Zip',
    'Address 1 - Country',
    'Address 1 - Type',
    'Address 2 - Street',
    'Address 2 - City',
    'Address 2 - State',
    'Address 2 - Zip',
    'Address 2 - Country',
    'Address 2 - Type',
    'Address 3 - Street',
    'Address 3 - City',
    'Address 3 - State',
    'Address 3 - Zip',
    'Address 3 - Country',
    'Address 3 - Type',
    'Address 4 - Street',
    'Address 4 - City',
    'Address 4 - State',
    'Address 4 - Zip',
    'Address 4 - Country',
    'Address 4 - Type',
    'Address 5 - Street',
    'Address 5 - City',
    'Address 5 - State',
    'Address 5 - Zip',
    'Address 5 - Country',
    'Address 5 - Type',
    'Address 6 - Street',
    'Address 6 - City',
    'Address 6 - State',
    'Address 6 - Zip',
    'Address 6 - Country',
    'Address 6 - Type',
    'Property Address',
    'Property City',
    'Property State',
    'Property Postal Code',
    'Property MLS Number',
    'Property Price',
    'Property Beds',
    'Property Baths',
    'Property Area',
    'Property Lot',
    'Message',
    'Description',
    'Notes',
    'Calls',
    'Texts',
    'Background',
    'Campaign Source',
    'Campaign Medium',
    'Campaign Term',
    'Campaign Content',
    'Campaign Name',
    'Deal Stage',
    'Deal Close Date',
    'Deal Price',
    'ID',
    'Birthday',
    'Closing Anniversary',
    'Date Reassigned',
    'Home Anniversary',
    'Huddle URL',
    'RealGeeks URL',
    'Timeframe',
    'Website',
    'Update Source',
    'Budget'
]]

# df_app_only.reset_index(inplace=True)

There are 6299 documents now in followupboss_people_backup
Deleted 6299 documents from followupboss_people_backup

Processing People from Followup boss: 100%|██████████| 64/64 [01:24<00:00,  1.31s/it]
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:122: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:122: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id.dropna(subset=['ID'], inplace=True)
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:126: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_people_id['ID'] = unique_people_id['ID'].astype(int)

length of rows of people from followup boss before merge: 6299
length of rows of people from followup boss after merge: 6299

C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:241: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Campaign Content'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:242: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Campaign Name'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:243: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Deal Stage'] = df_fub_only['dealStage']
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:244: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Deal Close Date'] = df_fub_only['dealCloseDate']
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:245: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Deal Price'] = df_fub_only['dealPrice']
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:247: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Birthday'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:248: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Closing Anniversary'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:249: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Date Reassigned'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Home Anniversary'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Huddle URL'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['RealGeeks URL'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:253: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Timeframe'] = None
C:\Users\ENDUSER\AppData\Local\Temp\ipykernel_10500\4089505522.py:254: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_fub_only['Website'] = None

Error updating the sheet: Out of range float values are not JSON compliant
Overwritten Leads

In [192]:
df_final = pd.concat([df_fub_only, df_app_only], ignore_index=True)
# df_final.drop(['index'], axis=1, inplace=True)

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Copy of Leads 2")

sheet.clear()

# df_final = df_final.replace('', None)
# df_final.replace('NaN', '', inplace=True)
# df_final = df_final.replace([np.inf, -np.inf], None)
# df_final.fillna('', inplace=True)
df_final.replace([np.nan, None, 'NaN'], '', inplace=True)
# df_final = df_final.astype(str).replace('nan', '')  # Replace string 'nan' with empty string
# df_final.drop('_id', axis=1, inplace=True)
# df_final.drop('level_0', axis=1, inplace=True)

df_final_snap = df_final.copy()
df_final['Tags'] = df_final['Tags'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
df_final['Tags'].value_counts()

# for col in df_final.select_dtypes(include=['object']).columns:
#     df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
# data = [df_final.columns.values.tolist()] + df_final.values.tolist()
# data = [df_final.columns.values.tolist()] + df_final.astype(str).values.tolist()

data = df_final.values.tolist()
data.insert(0, df_final.columns.tolist())  # Add header

# Update the Google Sheet with the data
# try:
#     sheet.update(data)
#     print("Overwritten Leads")
# except Exception as e:
#     print("Error updating the sheet:", e)

sheet.update(data)

print("Overwritten Leads")

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial

# with open(logfile, 'a') as file:
#     file.write(f'\nTotal Number of leads: {len(df_final)} in the collection {collection.name}')
#     file.write(f'\nUpdate Leads Gsheet End time in USA: {current_time}')
#     file.write(f'\nUpdate Leads Gsheet End time in PH: {current_time_ph}\n')
#     file.write(f'\nUpdate Leads Gsheet Total Running time: {total_running_time}')

Overwritten Leads

In [193]:
df_final_snap['Lead ID'].dtype

dtype('O')

In [3]:
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from datetime import datetime as dt

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

# with open(logfile, 'a') as file:
#     file.write(f'\nPeople Relationships Extract Start time in USA: {current_time_initial}')
#     file.write(f'\nPeople Relationships Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/users?limit=100&offset=0&includeDeleted=true"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
with open(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\people_relationships.json', 'w') as file:
    json.dump(data, file, indent=4)
    
total = data['_metadata']['total']
list_of_offsets = list(range(0, round(total, -1) + 1, 100))

df_list = []

from pymongo import MongoClient
client = MongoClient()
db = client['Christina']
collection = db['followupboss_users']

initial_count_of_collection = collection.count_documents({})

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_documents():
    # print(f"There are {collection.count_documents({})} documents now in {collection.name}")
    return collection.count_documents({})

delete_all()
for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
    url = f"https://api.followupboss.com/v1/users?limit=100&offset={i}&includeDeleted=true"

    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['users']:
        if isinstance(x, dict):
            insert_one_document(x)

final_count_of_collection = count_of_all_documents() - initial_count_of_collection
print(f'Added {final_count_of_collection} in the collection {collection.name}')
print(f'Total Number of documents: {count_of_all_documents()} in the collection {collection.name}')

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

# with open(logfile, 'a') as file:
#     file.write(f'\nTotal Number of documents: {count_of_all_documents()} in the collection {collection.name}')
#     file.write(f'\nPeople Relationships Extract End time in USA: {current_time}')
#     file.write(f'\nPeople Relationships Extract End time in PH: {current_time_ph}\n')
#     file.write(f'\nPeople Relationships Total Running time: {total_running_time}')

Deleted 0 documents from followupboss_users

Processing People from Followup boss: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]

Added 8 in the collection followupboss_users
Total Number of documents: 8 in the collection followupboss_users

In [2]:
from datetime import datetime as dt
import requests
import json
import pandas as pd
import base64
from tqdm import tqdm
import pytz
from pymongo import MongoClient
import gspread
from google.oauth2.service_account import Credentials
import uuid
import numpy as np

hoover_tz = pytz.timezone('America/Chicago')

current_time_initial = dt.now(hoover_tz)
current_time_ph_initial = dt.now()
logfile = r'c:\\Users\\ENDUSER\\OneDrive\\FOR CHRISTINA\\Python\\ETLs\\followupboss\\logs.txt'

with open(logfile, 'a') as file:
    file.write(f'\nPeople Extract Start time in USA: {current_time_initial}')
    file.write(f'\nPeople Extract Start time in PH: {current_time_ph_initial}\n')

# Your API key
api_key = "fka_0fEZ6mLXysLcr5c3wVKxUUnKgRTHQwftdg"
X_System_Key = "ad593739c6d8eb43684c90ef2d98d08f"
X_System = "Christina_James"

# Encode API key in Base64
encoded_api_key = base64.b64encode(api_key.encode('utf-8')).decode('utf-8')

# API endpoint and query parameters
url = "https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset=0&includeTrash=false&includeUnclaimed=false"

r = requests.get(url, headers={'accept': "application/json",
                               'Authorization': "Basic " + encoded_api_key,
                                'X-System-Key': X_System_Key,
                                'X-System': X_System
})
data = r.json()
total = data["_metadata"]["total"]

client = MongoClient()
db = client['Christina']
collection = db['followupboss_people']

def delete_all():
    result = collection.delete_many({})
    print(f"Deleted {result.deleted_count} documents from {collection.name}")

def insert_one_document(data):
    collection.insert_one(data)

def count_of_all_collections():
    return collection.count_documents({})    

initial_count = count_of_all_collections()
print(f"There are {initial_count} documents now in {collection.name}")

delete_all()

list_of_offsets = list(range(0, round(total, -2) + 1, 100))
date_now = dt.today().strftime('%m/%d/%Y')

for i in tqdm(list_of_offsets, total=len(list_of_offsets), desc="Processing People from Followup boss", leave=True):
    url = f'https://api.followupboss.com/v1/people?sort=lastActivity&limit=100&offset={i}&includeTrash=false&includeUnclaimed=false'
    r = requests.get(url, headers={'accept': "application/json",
                                'Authorization': "Basic " + encoded_api_key,
                                    'X-System-Key': X_System_Key,
                                    'X-System': X_System
    })
    data = r.json()
    for x in data['people']:
        if isinstance(x, dict):
            insert_one_document(x)

def get_all_data_as_dataframe():
    # Retrieve all documents in the collection
    documents = list(collection.find({}))  # Convert the cursor to a list of dictionaries

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(documents)

    return df

df = get_all_data_as_dataframe()

# Limit the number of phones to 6
df['phones'] = df['phones'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['emails'] = df['emails'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])
df['addresses'] = df['addresses'].apply(lambda x: x[:6] if x is not None and len(x) > 0 else [])

# Create separate columns for the first 6 phones
for i in range(6):
    df[f'phone_{i+1}'] = df['phones'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'phone_type_{i+1}'] = df['phones'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'email_{i+1}'] = df['emails'].apply(lambda x: x[i]['value'] if len(x) > i else None)
    df[f'email_type_{i+1}'] = df['emails'].apply(lambda x: x[i]['type'] if len(x) > i else None)
    df[f'address_street_{i+1}'] = df['addresses'].apply(lambda x: x[i]['street'] if len(x) > i else None)
    df[f'address_city_{i+1}'] = df['addresses'].apply(lambda x: x[i]['city'] if len(x) > i else None)
    df[f'address_state_{i+1}'] = df['addresses'].apply(lambda x: x[i]['state'] if len(x) > i else None)
    df[f'address_code_{i+1}'] = df['addresses'].apply(lambda x: x[i]['code'] if len(x) > i else None)
    df[f'address_country_{i+1}'] = df['addresses'].apply(lambda x: x[i]['country'] if len(x) > i else None)
    df[f'address_type_{i+1}'] = df['addresses'].apply(lambda x: x[i]['type'] if len(x) > i else None)

# Drop the original 'phones' column if not needed
df.drop(columns=['phones'], inplace=True)
df.drop(columns=['emails'], inplace=True)
df.drop(columns=['addresses'], inplace=True)

# Display the DataFrame
df['Update Source'] = "Followup boss"

SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)
client = gspread.authorize(creds)
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")
data = sheet.get_all_values()
df_leads = pd.DataFrame(data[1:], columns=data[0])

unique_people_id = df_leads[['Lead ID', 'ID']]
unique_people_id['ID'].replace(r'^\s*$', float('NaN'), regex=True, inplace=True)
unique_people_id.dropna(subset=['ID'], inplace=True)

df['id'] = df['id'].astype(int)
unique_people_id['ID'] = unique_people_id['ID'].astype(int)

print(f'length of rows of people from followup boss before merge: {len(df)}')
df_new = pd.merge(df, unique_people_id, 'left', left_on='id', right_on='ID')
print(f'length of rows of people from followup boss after merge: {len(df)}')

def generate_lead_id():
    return str(uuid.uuid4())[:8]

df_new ['Lead ID']= df_new['Lead ID'].apply(lambda x: generate_lead_id() if pd.isna(x) else x)
df_new.replace([np.inf, -np.inf, np.nan], None, inplace=True)

df_new['Budget'] = df_new['price']

df_app_only = df_leads[df_leads['Update Source'] == 'App']

df_fub_only = df_new[~df_new['Lead ID'].isin(df_app_only['Lead ID'])]
df_fub_only['Update Source'] = 'Followup boss'
# df_fub_only2 = df_fub_only.copy()
# df_fub_only = df_fub_only2.copy()

df_fub_only['Lead ID'] = df_fub_only['Lead ID']
df_fub_only['Year'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%Y')
df_fub_only['Month'] = pd.to_datetime(df_fub_only['created']).dt.strftime('%b')
df_fub_only['Agent ID'] = df_fub_only['assignedUserId']
df_fub_only['Date Added'] = pd.to_datetime(df_fub_only['created'])
df_fub_only['Name'] = df_fub_only['firstName'] + ' ' + df_fub_only['lastName']
df_fub_only['First Name'] = df_fub_only['firstName']
df_fub_only['Last Name'] = df_fub_only['lastName']
df_fub_only['Stage'] = df_fub_only['stage']
df_fub_only['Lead Source'] = df_fub_only['source']
df_fub_only['Assigned To'] = df_fub_only['assignedTo']
df_fub_only['Last Assigned'] = df_fub_only['updated']
df_fub_only['Is Contacted'] = df_fub_only['contacted']
df_fub_only['Listing Price'] = df_fub_only['price']
df_fub_only['Tags'] = df_fub_only['tags']
df_fub_only['Email 1'] = df_fub_only['email_1']
df_fub_only['Email 1 - Type'] = df_fub_only['email_type_1']
df_fub_only['Email 2'] = df_fub_only['email_2']
df_fub_only['Email 2 - Type'] = df_fub_only['email_type_2']
df_fub_only['Email 3'] = df_fub_only['email_3']
df_fub_only['Email 3 - Type'] = df_fub_only['email_type_3']
df_fub_only['Email 4'] = df_fub_only['email_4']
df_fub_only['Email 4 - Type'] = df_fub_only['email_type_4']
df_fub_only['Email 5'] = df_fub_only['email_5']
df_fub_only['Email 5 - Type'] = df_fub_only['email_type_5']
df_fub_only['Email 6'] = df_fub_only['email_6']
df_fub_only['Email 6 - Type'] = df_fub_only['email_type_6']
df_fub_only['Phone 1'] = df_fub_only['phone_1']
df_fub_only['Phone 1 - Type'] = df_fub_only['phone_type_1']
df_fub_only['Phone 2'] = df_fub_only['phone_2']
df_fub_only['Phone 2 - Type'] = df_fub_only['phone_type_2']
df_fub_only['Phone 3'] = df_fub_only['phone_3']
df_fub_only['Phone 3 - Type'] = df_fub_only['phone_type_3']
df_fub_only['Phone 4'] = df_fub_only['phone_4']
df_fub_only['Phone 4 - Type'] = df_fub_only['phone_type_4']
df_fub_only['Phone 5'] = df_fub_only['phone_5']
df_fub_only['Phone 5 - Type'] = df_fub_only['phone_type_5']
df_fub_only['Phone 6'] = df_fub_only['phone_6']
df_fub_only['Phone 6 - Type'] = df_fub_only['phone_type_6']
df_fub_only['Address 1 - Street'] = df_fub_only['address_street_1']
df_fub_only['Address 1 - City'] = df_fub_only['address_city_1']
df_fub_only['Address 1 - State'] = df_fub_only['address_state_1']
df_fub_only['Address 1 - Zip'] = df_fub_only['address_code_1']
df_fub_only['Address 1 - Country'] = df_fub_only['address_country_1']
df_fub_only['Address 1 - Type'] = df_fub_only['address_type_1']
df_fub_only['Address 2 - Street'] = df_fub_only['address_street_2']
df_fub_only['Address 2 - City'] = df_fub_only['address_city_2']
df_fub_only['Address 2 - State'] = df_fub_only['address_state_2']
df_fub_only['Address 2 - Zip'] = df_fub_only['address_code_2']
df_fub_only['Address 2 - Country'] = df_fub_only['address_country_2']
df_fub_only['Address 2 - Type'] = df_fub_only['address_type_2']
df_fub_only['Address 3 - Street'] = df_fub_only['address_street_3']
df_fub_only['Address 3 - City'] = df_fub_only['address_city_3']
df_fub_only['Address 3 - State'] = df_fub_only['address_state_3']
df_fub_only['Address 3 - Zip'] = df_fub_only['address_code_3']
df_fub_only['Address 3 - Country'] = df_fub_only['address_country_3']
df_fub_only['Address 3 - Type'] = df_fub_only['address_type_3']
df_fub_only['Address 4 - Street'] = df_fub_only['address_street_4']
df_fub_only['Address 4 - City'] = df_fub_only['address_city_4']
df_fub_only['Address 4 - State'] = df_fub_only['address_state_4']
df_fub_only['Address 4 - Zip'] = df_fub_only['address_code_4']
df_fub_only['Address 4 - Country'] = df_fub_only['address_country_4']
df_fub_only['Address 4 - Type'] = df_fub_only['address_type_4']
df_fub_only['Address 5 - Street'] = df_fub_only['address_street_5']
df_fub_only['Address 5 - City'] = df_fub_only['address_city_5']
df_fub_only['Address 5 - State'] = df_fub_only['address_state_5']
df_fub_only['Address 5 - Zip'] = df_fub_only['address_code_5']
df_fub_only['Address 5 - Country'] = df_fub_only['address_country_5']
df_fub_only['Address 5 - Type'] = df_fub_only['address_type_5']
df_fub_only['Address 6 - Street'] = df_fub_only['address_street_6']
df_fub_only['Address 6 - City'] = df_fub_only['address_city_6']
df_fub_only['Address 6 - State'] = df_fub_only['address_state_6']
df_fub_only['Address 6 - Zip'] = df_fub_only['address_code_6']
df_fub_only['Address 6 - Country'] = df_fub_only['address_country_6']
df_fub_only['Address 6 - Type'] = df_fub_only['address_type_6']
df_fub_only['Property Address'] = None
df_fub_only['Property City'] = None
df_fub_only['Property State'] = None
df_fub_only['Property Postal Code'] = None
df_fub_only['Property MLS Number'] = None
df_fub_only['Property Price'] = None
df_fub_only['Property Beds'] = None
df_fub_only['Property Baths'] = None
df_fub_only['Property Area'] = None
df_fub_only['Property Lot'] = None
df_fub_only['Message'] = None
df_fub_only['Description'] = None
df_fub_only['Notes'] = None
df_fub_only['Calls'] = None
df_fub_only['Texts'] = None
df_fub_only['Background'] = None
df_fub_only['Campaign Source'] = None
df_fub_only['Campaign Medium'] = None
df_fub_only['Campaign Term'] = None
df_fub_only['Campaign Content'] = None
df_fub_only['Campaign Name'] = None
df_fub_only['Deal Stage'] = df_fub_only['dealStage']
df_fub_only['Deal Close Date'] = df_fub_only['dealCloseDate']
df_fub_only['Deal Price'] = df_fub_only['dealPrice']
df_fub_only['ID'] = df_fub_only['id']
df_fub_only['Birthday'] = None
df_fub_only['Closing Anniversary'] = None
df_fub_only['Date Reassigned'] = None
df_fub_only['Home Anniversary'] = None
df_fub_only['Huddle URL'] = None
df_fub_only['RealGeeks URL'] = None
df_fub_only['Timeframe'] = None
df_fub_only['Website'] = None
df_fub_only['Update Source'] = df_fub_only['Update Source']
df_fub_only['Budget'] = df_fub_only['price']

df_fub_only = df_fub_only[[
    'Lead ID',
    'Year',
    'Month',
    'Agent ID',
    'Date Added',
    'Name',
    'First Name',
    'Last Name',
    'Stage',
    'Lead Source',
    'Assigned To',
    'Last Assigned',
    'Is Contacted',
    'Listing Price',
    'Tags',
    'Email 1',
    'Email 1 - Type',
    'Email 2',
    'Email 2 - Type',
    'Email 3',
    'Email 3 - Type',
    'Email 4',
    'Email 4 - Type',
    'Email 5',
    'Email 5 - Type',
    'Email 6',
    'Email 6 - Type',
    'Phone 1',
    'Phone 1 - Type',
    'Phone 2',
    'Phone 2 - Type',
    'Phone 3',
    'Phone 3 - Type',
    'Phone 4',
    'Phone 4 - Type',
    'Phone 5',
    'Phone 5 - Type',
    'Phone 6',
    'Phone 6 - Type',
    'Address 1 - Street',
    'Address 1 - City',
    'Address 1 - State',
    'Address 1 - Zip',
    'Address 1 - Country',
    'Address 1 - Type',
    'Address 2 - Street',
    'Address 2 - City',
    'Address 2 - State',
    'Address 2 - Zip',
    'Address 2 - Country',
    'Address 2 - Type',
    'Address 3 - Street',
    'Address 3 - City',
    'Address 3 - State',
    'Address 3 - Zip',
    'Address 3 - Country',
    'Address 3 - Type',
    'Address 4 - Street',
    'Address 4 - City',
    'Address 4 - State',
    'Address 4 - Zip',
    'Address 4 - Country',
    'Address 4 - Type',
    'Address 5 - Street',
    'Address 5 - City',
    'Address 5 - State',
    'Address 5 - Zip',
    'Address 5 - Country',
    'Address 5 - Type',
    'Address 6 - Street',
    'Address 6 - City',
    'Address 6 - State',
    'Address 6 - Zip',
    'Address 6 - Country',
    'Address 6 - Type',
    'Property Address',
    'Property City',
    'Property State',
    'Property Postal Code',
    'Property MLS Number',
    'Property Price',
    'Property Beds',
    'Property Baths',
    'Property Area',
    'Property Lot',
    'Message',
    'Description',
    'Notes',
    'Calls',
    'Texts',
    'Background',
    'Campaign Source',
    'Campaign Medium',
    'Campaign Term',
    'Campaign Content',
    'Campaign Name',
    'Deal Stage',
    'Deal Close Date',
    'Deal Price',
    'ID',
    'Birthday',
    'Closing Anniversary',
    'Date Reassigned',
    'Home Anniversary',
    'Huddle URL',
    'RealGeeks URL',
    'Timeframe',
    'Website',
    'Update Source',
    'Budget'
]]

# df_app_only.reset_index(inplace=True)

df_final = pd.concat([df_fub_only, df_app_only], ignore_index=True)
# df_final.drop(['index'], axis=1, inplace=True)

# Define the scope (read-only access to Sheets)
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

# Load the service account credentials
creds = Credentials.from_service_account_file(r'C:\Users\ENDUSER\OneDrive\FOR CHRISTINA\Python\ETLs\credentials.json', scopes=SCOPES)

# Authorize the client with the credentials
client = gspread.authorize(creds)

# Open the Google Sheet by name or by URL
sheet = client.open_by_key("1UAtfmU1LSsIvfFBDdS0cpUrrhsW9ZDC0mDKF1kj8Ato").worksheet("Leads")

sheet.clear()

# df_final = df_final.replace('', None)
# df_final.replace('NaN', '', inplace=True)
# df_final = df_final.replace([np.inf, -np.inf], None)
# df_final.fillna('', inplace=True)
df_final.replace([np.nan, None, 'NaN'], '', inplace=True)
# df_final = df_final.astype(str).replace('nan', '')  # Replace string 'nan' with empty string
# df_final.drop('_id', axis=1, inplace=True)
# df_final.drop('level_0', axis=1, inplace=True)

df_final_snap = df_final.copy()
df_final['Tags'] = df_final['Tags'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
df_final['Tags'].value_counts()

# for col in df_final.select_dtypes(include=['object']).columns:
#     df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
# data = [df_final.columns.values.tolist()] + df_final.values.tolist()
# data = [df_final.columns.values.tolist()] + df_final.astype(str).values.tolist()

data = df_final.values.tolist()
data.insert(0, df_final.columns.tolist())  # Add header

# Update the Google Sheet with the data
# try:
#     sheet.update(data)
#     print("Overwritten Leads")
# except Exception as e:
#     print("Error updating the sheet:", e)

sheet.update(data)

print("Overwritten Leads")

hoover_tz = pytz.timezone('America/Chicago')

current_time = dt.now(hoover_tz)
current_time_ph = dt.now()
total_running_time = current_time_ph - current_time_ph_initial

with open(logfile, 'a') as file:
    file.write(f'\nTotal Number of leads: {len(df_final)} in the collection {collection.name}')
    file.write(f'\nUpdate Leads Gsheet End time in USA: {current_time}')
    file.write(f'\nUpdate Leads Gsheet End time in PH: {current_time_ph}\n')
    file.write(f'\nUpdate Leads Gsheet Total Running time: {total_running_time}')

{'_metadata': {'collection': 'users',
  'offset': 0,
  'limit': 100,
  'total': 8,
  'next': None,
  'nextLink': None},
 'users': [{'id': 7,
   'created': '2023-06-16T15:33:54Z',
   'updated': '2024-10-22T21:15:45Z',
   'name': 'Jaki Ahlemeyer',
   'firstName': 'Jaki',
   'lastName': 'Ahlemeyer',
   'email': 'jaki@cljteam.com',
   'phone': '205-201-8863',
   'role': 'Agent',
   'status': 'Active',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': {'original': 'https://s.followupboss.com/public_attachments/20790692-4da2-446f-a293-0b921bd9e955.jpeg',
    '162x162': 'https://s.followupboss.com/pictures/33e5b2f5-138c-4701-98be-a690bfb9bb94.jpeg',
    '60x60': 'https://s.followupboss.com/pictures/76ef9ead-462a-454f-ba1d-fc26326a24ec.jpeg',
    '40x40': 'https://s.followupboss.com/pictures/9589d2f4-563d-49b3-a3f7-2569460d5bbf.jpeg',
    '30x30': 'https://s.followupboss.com/pictures/b6478173-dfa8-42c6-be66-e46157efa5aa.jpeg',
    '26x26': 'https://s.followupboss.com/pictures/6a4d0bf0-56b4-4abf-af36-9cddf531da28.jpeg'},
   'pauseLeadDistribution': False,
   'lastSeenIos': '2024-10-24T14:42:18Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2024-10-22T21:20:48Z',
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [{'id': 5, 'name': 'Equal Distribution'}],
   'leadEmailAddress': 'jaki@followupboss.me'},
  {'id': 6,
   'created': '2023-06-15T16:32:31Z',
   'updated': '2023-07-19T14:30:52Z',
   'name': 'Sue Willoughby',
   'firstName': 'Sue',
   'lastName': 'Willoughby',
   'email': 'sue@cljteam.com',
   'phone': '205-222-5959',
   'role': 'Agent',
   'status': 'Deleted',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': [],
   'pauseLeadDistribution': False,
   'lastSeenIos': '2023-07-09T22:25:12Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2023-07-05T16:15:25Z',
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'sue-willoughby-2114677002-6@leads.followupboss.com'},
  {'id': 5,
   'created': '2023-05-29T23:59:39Z',
   'updated': '2024-03-08T17:27:57Z',
   'name': 'Maggie Asuncion',
   'firstName': 'Maggie',
   'lastName': 'Asuncion',
   'email': 'maggie@cljteam.com',
   'phone': '',
   'role': 'Broker',
   'status': 'Active',
   'timezone': 'Asia/Manila',
   'beta': True,
   'picture': {'original': 'https://s.followupboss.com/public_attachments/b551d510-b325-4fc8-b347-10fe07d0aa59.jpeg',
    '162x162': 'https://s.followupboss.com/pictures/cdeb7f5e-85b8-475b-a5f2-7c98883ba38a.jpeg',
    '60x60': 'https://s.followupboss.com/pictures/f75eb609-b264-4f96-abfd-f4d9eff41d1c.jpeg',
    '40x40': 'https://s.followupboss.com/pictures/ffa7438b-7eba-4a9b-85e2-0c635da37ab9.jpeg',
    '30x30': 'https://s.followupboss.com/pictures/8659b2cf-0b7f-4702-aef4-4d351939aa66.jpeg',
    '26x26': 'https://s.followupboss.com/pictures/93512f4a-08ea-4803-8df6-7a90a8be0a2c.jpeg'},
   'pauseLeadDistribution': False,
   'lastSeenIos': '2024-01-06T07:38:13Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2024-05-05T04:30:02Z',
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'maggie.asuncion@followupboss.me'},
  {'id': 4,
   'created': '2023-05-23T11:59:45Z',
   'updated': '2023-06-26T15:53:57Z',
   'name': 'Team James',
   'firstName': 'Team',
   'lastName': 'James',
   'email': 'christina@christinajamesteam.com',
   'phone': '205-965-6483',
   'role': 'Agent',
   'status': 'Deleted',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': [],
   'pauseLeadDistribution': False,
   'lastSeenIos': '2023-06-12T21:00:45Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2023-06-12T21:02:54Z',
   'canExport': True,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'team-james-2114677002-4@leads.followupboss.com'},
  {'id': 3,
   'created': '2023-05-22T15:59:34Z',
   'updated': '2024-04-12T15:32:04Z',
   'name': 'Hannah Dean',
   'firstName': 'Hannah',
   'lastName': 'Dean',
   'email': 'christina@christinajamesteam.com',
   'phone': '205-876-4401',
   'role': 'Agent',
   'status': 'Deleted',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': [],
   'pauseLeadDistribution': True,
   'lastSeenIos': '2024-04-12T12:01:03Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2024-03-02T13:06:22Z',
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'hannah-dean-2114677002-3@leads.followupboss.com'},
  {'id': 2,
   'created': '2023-05-22T15:59:29Z',
   'updated': '2024-05-08T19:41:23Z',
   'name': 'Anne Banks',
   'firstName': 'Anne',
   'lastName': 'Banks',
   'email': 'anne@cljteam.com',
   'phone': '2058731234',
   'role': 'Agent',
   'status': 'Deleted',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': [],
   'pauseLeadDistribution': True,
   'lastSeenIos': '2024-05-08T00:22:19Z',
   'lastSeenAndroid': None,
   'lastSeenFub2': '2024-04-11T18:14:38Z',
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'anne-banks-2114677002-2@leads.followupboss.com'},
  {'id': 1,
   'created': '2023-05-15T00:40:31Z',
   'updated': '2024-10-23T19:19:01Z',
   'name': 'Christina James',
   'firstName': 'Christina',
   'lastName': 'James',
   'email': 'christina@cljteam.com',
   'phone': '2059656483',
   'role': 'Broker',
   'status': 'Active',
   'timezone': 'America/Chicago',
   'beta': True,
   'picture': {'original': 'https://s.followupboss.com/public_attachments/d27cae00-7b44-407f-aacf-0f5cb9c5e78f.png',
    '162x162': 'https://s.followupboss.com/pictures/7a3ea8f9-fa7e-4017-a800-2288d8c5c78b.png',
    '60x60': 'https://s.followupboss.com/pictures/c85b1dae-46a9-4b98-9d59-1bb3a95637a6.png',
    '40x40': 'https://s.followupboss.com/pictures/58c325b0-2984-4030-8e94-78348b6e66cc.png',
    '30x30': 'https://s.followupboss.com/pictures/8052951f-9096-44c9-8f00-e94e766638f8.png',
    '26x26': 'https://s.followupboss.com/pictures/b743666a-7fc6-42a5-97bc-3fc113dd72ac.png'},
   'pauseLeadDistribution': False,
   'lastSeenIos': '2024-10-24T13:01:24Z',
   'lastSeenAndroid': '2024-05-03T12:15:18Z',
   'lastSeenFub2': '2024-10-24T14:56:32Z',
   'canExport': True,
   'canCreateApiKeys': True,
   'isOwner': True,
   'groups': [{'id': 1, 'name': 'Team Lowry'},
    {'id': 2, 'name': 'Seller Leads'},
    {'id': 5, 'name': 'Equal Distribution'}],
   'leadEmailAddress': 'christina.lowry@followupboss.me'},
  {'id': -1,
   'created': '2023-05-15T00:40:31Z',
   'updated': '2023-05-15T00:40:31Z',
   'name': 'Follow Up Boss',
   'firstName': 'Follow Up',
   'lastName': 'Boss',
   'email': 'client_93473@followupboss.com',
   'phone': '',
   'role': 'Broker',
   'status': 'Active',
   'timezone': 'Europe/Kiev',
   'beta': True,
   'picture': [],
   'pauseLeadDistribution': False,
   'lastSeenIos': None,
   'lastSeenAndroid': None,
   'lastSeenFub2': None,
   'canExport': False,
   'canCreateApiKeys': True,
   'isOwner': False,
   'groups': [],
   'leadEmailAddress': 'follow-up-boss-2114677002--1@leads.followupboss.com'}]}

In [7]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient()
db = client['Christina']
collection = db['followupboss_events']

list_of_events = collection.find({})
df = pd.json_normalize(list_of_events, sep='_')
df

,_id,additional,created,description,id,message,noteId,occurred,pageDuration,pageTitle,...,property_lot,property_lat,property_lng,property,additional_custom_Area,additional_custom_Most Recent Search,additional_custom_How Soon,additional_custom_Assigned Agent,additional_custom_Address,additional_custom_Condition
0,671bcab11ed18c62f66902fd,[],2024-10-25T16:19:29Z,"MLS#21393443 - $362,500 - 4048 Laurel Ridge Tr...",95868,,NaN,2024-10-25T16:19:29Z,0,None,...,NaN,33.609806,-86.565506,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,671bcab11ed18c62f66902fe,[],2024-10-25T16:17:26Z,,95867,,NaN,2024-10-25T16:17:26Z,0,None,...,NaN,33.609806,-86.565506,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,671bcab11ed18c62f66902ff,[],2024-10-25T16:15:20Z,,95866,,NaN,2024-10-25T16:15:20Z,0,None,...,NaN,33.632435,-86.608376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,671bcab11ed18c62f6690300,[],2024-10-25T16:14:01Z,,95864,,NaN,2024-10-25T16:14:01Z,0,None,...,NaN,33.602543,-86.598969,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,671bcab11ed18c62f6690301,[],2024-10-25T16:13:20Z,,95863,,NaN,2024-10-25T16:13:20Z,0,None,...,NaN,33.684914,-86.590187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,671bcdb01ed18c62f6690d01,[],2024-09-30T11:11:58Z,,93172,,NaN,2024-09-30T11:11:58Z,0,None,...,NaN,33.521858,-86.338669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2565,671bcdb01ed18c62f6690d02,[],2024-09-30T11:11:49Z,,93171,,NaN,2024-09-30T11:11:49Z,0,None,...,NaN,33.336323,-86.618156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2566,671bcdb01ed18c62f6690d03,[],2024-09-30T11:11:36Z,,93170,,NaN,2024-09-30T11:11:36Z,0,None,...,NaN,33.360748,-86.820251,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2567,671bcdb01ed18c62f6690d04,[],2024-09-30T11:11:25Z,First visit since 2024-09-29 10:41:53 UTC,93169,,NaN,2024-09-30T11:11:25Z,0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2568,671bcdb01ed18c62f6690d05,[],2024-09-30T11:11:24Z,,93168,,NaN,2024-09-30T11:11:24Z,0,None,...,NaN,33.390491,-86.677574,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df['source'].value_counts()
df['type'].value_counts()

type
Viewed Property           1321
Visited Website            602
Property Search            312
Viewed Property Report     101
Saved Property              88
Registration                64
Saved Property Search       34
General Inquiry             19
Seller Inquiry              18
Property Inquiry            10
Name: count, dtype: int64

In [6]:
saved_properties = df[df['type'] == "Saved Property"]
saved_properties['property_id'].value_counts()

property_id
2935.0     2
12852.0    2
14038.0    2
14073.0    2
883.0      2
          ..
14204.0    1
14196.0    1
14195.0    1
13780.0    1
12805.0    1
Name: count, Length: 63, dtype: int64

In [1]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient()
db = client['Christina']
collection = db['followupboss_people']

list_of_events = collection.find({})
df = pd.json_normalize(list_of_events, sep='_')
df

,_id,id,created,updated,createdVia,lastActivity,name,firstName,lastName,stage,...,socialData_company,socialData_title,socialData_bio,socialData_topics,socialData_facebook,socialData_twitter,socialData_googleProfile,socialData_googlePlus,socialData_linkedIn,picture_small
0,671a6351dc5436d5466b5606,8739,2023-06-20T19:11:58Z,2023-06-20T20:50:23Z,Manually,2023-06-20T20:50:23Z,Follow Up Boss Customer Service,Follow Up Boss,Customer Service,Vendors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,671a6351dc5436d5466b5607,10445,2023-06-21T18:28:02Z,2023-06-21T18:32:19Z,Manually,2023-06-21T23:37:30Z,Matria Chapple,Matria,Chapple,Referral Partners,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,671a6351dc5436d5466b5608,12213,2023-07-24T20:22:40Z,2023-07-24T20:23:31Z,Manually,2023-07-24T20:25:09Z,Bianca Villalta,Bianca,Villalta,Vendors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,671a6351dc5436d5466b5609,12212,2023-07-24T20:21:21Z,2023-07-25T15:43:37Z,Manually,2023-07-25T15:43:37Z,Sasha Geotrarget,Sasha,Geotrarget,Vendors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,671a6351dc5436d5466b560a,8711,2023-06-14T16:15:36Z,2023-07-26T16:56:34Z,Email Parsing,2023-07-26T16:56:34Z,Krish,Krish,,Contact,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6293,671a639adc5436d5466b6e9b,5530,2020-02-07T06:10:00Z,2024-10-13T09:41:18Z,Import,2024-10-24T14:23:46Z,Jerry & Gayle Carder,Jerry & Gayle,Carder,B - Warm 3-6 Months,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6294,671a639adc5436d5466b6e9c,12776,2024-02-24T15:11:09Z,2024-08-02T20:55:18Z,Manually,2024-10-24T14:47:08Z,Roxanne Wing,Roxanne,Wing,C - Cold 6-12 Months,...,,,,,,https://twitter.com/rlwjazz,,,,NaN
6295,671a639adc5436d5466b6e9d,8624,2022-03-03T15:45:00Z,2024-10-18T12:59:34Z,Import,2024-10-24T14:53:31Z,Virat Patel,Virat,Patel,Contact,...,,,,,,,,,https://www.linkedin.com/in/dipanki-patel-5a7b...,NaN
6296,671a639adc5436d5466b6e9e,12221,2023-07-25T18:16:13Z,2024-10-17T13:56:34Z,Manually,2024-10-24T14:53:31Z,Harry Patel,Harry,Patel,A - Hot 1-3 Months,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6297,671a639adc5436d5466b6e9f,5910,2021-02-08T08:17:00Z,2024-10-16T19:22:47Z,Import,2024-10-24T15:01:31Z,Aquilla Cook,Aquilla,Cook,Active Client,...,Boeing,Business And Planning Analyst,Here you have permission to think...experience...,,,https://twitter.com/PriscillaPauley,,,https://www.linkedin.com/in/priscillapauley,https://s.followupboss.com/pictures/a1faae92fd...

In [6]:
df['createdVia'].value_counts()

createdVia
Import                    4498
API                       1282
Manually                   234
Email Parsing              203
Historic Email Parsing      81
Name: count, dtype: int64

In [16]:
df['created'] = pd.to_datetime(df['created'])
df['Month'] = df['created'].dt.month
df['Year'] = df['created'].dt.year
df['Month - Year'] = df['created'].dt.month.astype('str') + " - " + df['created'].dt.year.astype('str')
df_months = df['Month - Year'].value_counts().reset_index()
df_months

    Month - Year  count
0       6 - 2023   2675
1       5 - 2023    623
2       7 - 2023    145
3       8 - 2023    101
4       1 - 2022     82
..           ...    ...
105    10 - 2016      1
106    12 - 2014      1
107     1 - 2016      1
108     2 - 2016      1
109    11 - 2015      1

[110 rows x 2 columns]

In [19]:
df_months[df_months['Month - Year'] == "10 - 2024"]

   Month - Year  count
35    10 - 2024     39

In [3]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient("mongodb+srv://christina:akodcXC3gIB2qhYf@clusterchristina.57107.mongodb.net/")
db = client['Christina']
collection = db['app_leads_backup']

list_ = list(collection.find({}))
df = pd.DataFrame(list_)
df

,_id,Lead ID,Year,Month,Agent ID,Date Added,Name,First Name,Last Name,Stage,...,Birthday,Closing Anniversary,Date Reassigned,Home Anniversary,Huddle URL,RealGeeks URL,Timeframe,Website,Update Source,Budget
0,671367d5320d72fb79ebe896,e34ci82d,2024,Jun,A0,6/11/2024,Emberly Kouanvih,Emberly,Kouanvih,Lead,...,,,,,,,,,Followup boss,
1,671367d5320d72fb79ebe89c,b42nr21t,2024,Jun,A0,6/10/2024,Nounousyd Parissky,Nounousyd,Parissky,Lead,...,,,,,,,,,Followup boss,
2,671367d5320d72fb79ebe8a3,8af310d8,2024,Jun,A0,6/6/2024,Eanest Farrow,Earnest,Farrow,Active Client,...,6/6/2024,6/6/2024,6/6/2024,6/6/2024,,,,,App,
3,671367d5320d72fb79ebe8a4,l27mk33e,2024,Jun,A0,6/5/2024,Emily Leykum,Emily,Leykum,Past Client,...,,,,,,,,Buyer,Followup boss,
4,671367d5320d72fb79ebe8a8,o82hd58n,2024,Jun,A0,6/3/2024,Marc Wright,Marc,Wright,Email Only,...,,,,,,,,Seller,Followup boss,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6130,671367d5320d72fb79ec007c,404b25a6,2024,Jul,,7/18/2024,Aasiyah Salaam,,,,...,7/18/2024,7/18/2024,7/18/2024,7/18/2024,,,,,App,
6131,671367d5320d72fb79ec007d,455a3381,2024,Jul,,7/30/2024,,,,,...,7/30/2024,7/30/2024,7/30/2024,7/30/2024,,,,,App,
6132,671367d5320d72fb79ec007e,65d454e7,2024,Aug,,8/1/2024,,,,,...,8/1/2024,8/1/2024,8/1/2024,8/1/2024,,,,,App,
6133,671367d5320d72fb79ec0080,8f9b9822,2024,Aug,,8/1/2024,Alice Mazanec,,,,...,8/1/2024,8/1/2024,8/1/2024,8/1/2024,,,,,App,
6134,671367d5320d72fb79ec0085,b394479a,2024,Sep,,9/18/2024,Randy & Anne Rilling,,,,...,9/18/2024,9/18/2024,9/18/2024,9/18/2024,,,,,App,